package main

import (
	"context"
	"encoding/json"
	"fmt"
	"log/slog"
	"os"
	"time"

	"go.mongodb.org/mongo-driver/v2/bson"
	"go.mongodb.org/mongo-driver/v2/mongo"
	"go.mongodb.org/mongo-driver/v2/mongo/options"
	"golang.org/x/crypto/bcrypt"

	"quiz-battle/pkg/coins"
	"quiz-battle/pkg/coins/shop"
	"quiz-battle/pkg/log"
)

type Question struct {
	Text              string   `json:"text" bson:"text"`
	Options           []string `json:"options" bson:"options"`
	CorrectIndex      int      `json:"correctIndex" bson:"correctIndex"`
	Difficulty        string   `json:"difficulty" bson:"difficulty"`
	Topic             string   `json:"topic" bson:"topic"`
	AvgResponseTimeMs int      `json:"avgResponseTimeMs" bson:"avgResponseTimeMs"`
}

func main() {
	slog.SetDefault(log.Init("seed"))
	ctx, cancel := context.WithTimeout(context.Background(), 30*time.Second)
	defer cancel()

	mongoURI := os.Getenv("MONGO_URI")
	if mongoURI == "" {
		mongoURI = "mongodb://localhost:27017/quizbattle"
	}

	client, err := mongo.Connect(options.Client().ApplyURI(mongoURI))
	if err != nil {
		log.Fatal(ctx, "mongodb connect failed", "err", err)
	}
	defer client.Disconnect(ctx)

	db := client.Database(coins.DefaultDBName)

	// --- Create indexes ---
	log.FromContext(ctx).Info("creating indexes")

	usersColl := db.Collection("users")
	usersColl.Indexes().CreateOne(ctx, mongo.IndexModel{
		Keys:    bson.D{{Key: "username", Value: 1}},
		Options: options.Index().SetUnique(true),
	})
	usersColl.Indexes().CreateOne(ctx, mongo.IndexModel{
		Keys:    bson.D{{Key: "email", Value: 1}},
		Options: options.Index().SetUnique(true).SetSparse(true),
	})

	questionsColl := db.Collection("questions")
	questionsColl.Indexes().CreateOne(ctx, mongo.IndexModel{
		Keys: bson.D{{Key: "difficulty", Value: 1}},
	})

	db.Collection("match_history").Indexes().CreateOne(ctx, mongo.IndexModel{
		Keys:    bson.D{{Key: "roomId", Value: 1}},
		Options: options.Index().SetUnique(true),
	})
	db.Collection("match_history").Indexes().CreateOne(ctx, mongo.IndexModel{
		Keys: bson.D{{Key: "players.userId", Value: 1}},
	})

	// Phase 2 indexes
	usersColl.Indexes().CreateOne(ctx, mongo.IndexModel{
		Keys:    bson.D{{Key: "googleId", Value: 1}},
		Options: options.Index().SetUnique(true).SetSparse(true),
	})
	usersColl.Indexes().CreateOne(ctx, mongo.IndexModel{
		Keys:    bson.D{{Key: "referralCode", Value: 1}},
		Options: options.Index().SetUnique(true).SetSparse(true),
	})
	usersColl.Indexes().CreateOne(ctx, mongo.IndexModel{
		Keys: bson.D{{Key: "plan", Value: 1}, {Key: "planExpiresAt", Value: 1}},
	})

	paymentsColl := db.Collection("payments")
	paymentsColl.Indexes().CreateOne(ctx, mongo.IndexModel{
		Keys:    bson.D{{Key: "razorpayOrderId", Value: 1}},
		Options: options.Index().SetUnique(true),
	})
	paymentsColl.Indexes().CreateOne(ctx, mongo.IndexModel{
		Keys: bson.D{{Key: "userId", Value: 1}},
	})

	referralsColl := db.Collection("referrals")
	referralsColl.Indexes().CreateOne(ctx, mongo.IndexModel{
		Keys:    bson.D{{Key: "refereeId", Value: 1}},
		Options: options.Index().SetUnique(true),
	})
	referralsColl.Indexes().CreateOne(ctx, mongo.IndexModel{
		Keys: bson.D{{Key: "referrerId", Value: 1}},
	})

	db.Collection("tournaments").Indexes().CreateOne(ctx, mongo.IndexModel{
		Keys: bson.D{{Key: "startTime", Value: 1}, {Key: "status", Value: 1}},
	})
	// Phase 3 (4.2): the weekly auto-creation cron upserts on
	// (autoGenerated, weekKey). Sparse + unique gives us idempotency
	// without forbidding manually-seeded tournaments where weekKey is unset.
	db.Collection("tournaments").Indexes().CreateOne(ctx, mongo.IndexModel{
		Keys:    bson.D{{Key: "autoGenerated", Value: 1}, {Key: "weekKey", Value: 1}},
		Options: options.Index().SetUnique(true).SetSparse(true),
	})
	// Finalization-worker filter: status + endTime + winnersAwarded.
	db.Collection("tournaments").Indexes().CreateOne(ctx, mongo.IndexModel{
		Keys: bson.D{{Key: "status", Value: 1}, {Key: "endTime", Value: 1}, {Key: "winnersAwarded", Value: 1}},
	})

	// tournament_standings: per-(tournament, user) singleton + per-tournament ranking lookup.
	standingsColl := db.Collection("tournament_standings")
	standingsColl.Indexes().CreateOne(ctx, mongo.IndexModel{
		Keys:    bson.D{{Key: "tournamentId", Value: 1}, {Key: "userId", Value: 1}},
		Options: options.Index().SetUnique(true),
	})
	standingsColl.Indexes().CreateOne(ctx, mongo.IndexModel{
		// Score descending so the finalization worker's top-N query
		// (sort by score desc, limit N) hits the index leading edge.
		Keys: bson.D{{Key: "tournamentId", Value: 1}, {Key: "score", Value: -1}},
	})

	// tournament_payouts: durable work-list that backs the at-least-once
	// delivery of tournament.finished events. Unique key gives consumer-side
	// dedup; status index lets the drain worker sweep pending rows fast.
	payoutsColl := db.Collection("tournament_payouts")
	payoutsColl.Indexes().CreateOne(ctx, mongo.IndexModel{
		Keys:    bson.D{{Key: "tournamentId", Value: 1}, {Key: "userId", Value: 1}},
		Options: options.Index().SetUnique(true),
	})
	payoutsColl.Indexes().CreateOne(ctx, mongo.IndexModel{
		Keys: bson.D{{Key: "status", Value: 1}},
	})

	// Phase 3 (4.3): coin_ledger is the immutable source of truth for every
	// balance change. The unique compound index on (userId, refId, reason)
	// gives Grant its idempotency: calling Grant twice with the same refId
	// returns the existing row instead of double-crediting. The (userId,
	// createdAt desc) index is the read path for GetLedger pagination.
	ledgerColl := db.Collection("coin_ledger")
	if _, err := ledgerColl.Indexes().CreateMany(ctx, []mongo.IndexModel{
		{
			Keys:    bson.D{{Key: "userId", Value: 1}, {Key: "refId", Value: 1}, {Key: "reason", Value: 1}},
			Options: options.Index().SetUnique(true).SetName("uniq_user_ref_reason"),
		},
		{
			Keys:    bson.D{{Key: "userId", Value: 1}, {Key: "createdAt", Value: -1}},
			Options: options.Index().SetName("idx_user_recent"),
		},
	}); err != nil {
		log.Fatal(ctx, "coin_ledger indexes failed", "err", err)
	}
	log.FromContext(ctx).Info("coin_ledger indexes ensured")

	// §4.4 Friends & Challenges: the friend_requests collection holds one
	// row per (fromUserId, toUserId) pair. Unique compound prevents two
	// outbound requests in the same direction; the (toUserId, status) and
	// (fromUserId, status) indexes back the incoming/outgoing pending-list
	// queries.
	friendReqs := db.Collection("friend_requests")
	if _, err := friendReqs.Indexes().CreateMany(ctx, []mongo.IndexModel{
		{
			Keys:    bson.D{{Key: "fromUserId", Value: 1}, {Key: "toUserId", Value: 1}},
			Options: options.Index().SetUnique(true).SetName("uniq_from_to"),
		},
		{
			Keys:    bson.D{{Key: "toUserId", Value: 1}, {Key: "status", Value: 1}},
			Options: options.Index().SetName("idx_to_status"),
		},
		{
			Keys:    bson.D{{Key: "fromUserId", Value: 1}, {Key: "status", Value: 1}},
			Options: options.Index().SetName("idx_from_status"),
		},
		{
			// Symmetric reverse-direction lookup: SendFriendRequest queries
			// (fromUserId == target, toUserId == caller) before insert to
			// detect "Bob already sent Alice a request" and auto-accept it.
			// Without a leading toUserId index this would be a collection scan
			// on the rejected fall-through path. Today the leading-prefix of
			// uniq_from_to also serves the same query, but documenting and
			// creating the index makes the model contract honest and removes
			// the implicit dependency on uniq_from_to staying compound.
			Keys:    bson.D{{Key: "toUserId", Value: 1}, {Key: "fromUserId", Value: 1}},
			Options: options.Index().SetName("idx_to_from"),
		},
	}); err != nil {
		log.Fatal(ctx, "friend_requests indexes failed", "err", err)
	}
	log.FromContext(ctx).Info("friend_requests indexes ensured")

	// §4.4 Friends & Challenges: friend_challenge_outbox is the durable
	// queue for notif.friend.challenge pushes. The drainer in
	// services/scoring scans (processedAt == nil, createdAt asc) on a
	// 30s tick to retry rows stranded by a transient broker outage.
	if _, err := db.Collection("friend_challenge_outbox").Indexes().CreateOne(ctx, mongo.IndexModel{
		Keys:    bson.D{{Key: "processedAt", Value: 1}, {Key: "createdAt", Value: 1}},
		Options: options.Index().SetName("idx_outbox_pending"),
	}); err != nil {
		log.Fatal(ctx, "friend_challenge_outbox index failed", "err", err)
	}
	log.FromContext(ctx).Info("friend_challenge_outbox index ensured")

	// PR 4 (§4.3 Shop): the effect outbox is consumed by services/payment in
	// PR 5 to extend planExpiresAt for premium-trial purchases. The (kind,
	// processedAt asc) index lets the dequeuer's "find unprocessed by kind,
	// oldest first" query hit a covered scan.
	if _, err := db.Collection("coin_effect_outbox").Indexes().CreateOne(ctx, mongo.IndexModel{
		Keys:    bson.D{{Key: "processedAt", Value: 1}, {Key: "kind", Value: 1}},
		Options: options.Index().SetName("idx_outbox_due"),
	}); err != nil {
		log.Fatal(ctx, "coin_effect_outbox index failed", "err", err)
	}
	log.FromContext(ctx).Info("coin_effect_outbox index ensured")

	// §4.5 Deeper analytics — answer_log is one row per (user × question)
	// answered, populated by the scoring service's match-finished consumer
	// (services/scoring/main.go::persistMatch). The two indexes serve the
	// two query shapes the analytics RPCs use:
	//
	//   • (userId, createdAt desc) — response-time percentiles + 30-day
	//     time-window scan for monthly recap.
	//   • (userId, topic) — per-topic accuracy aggregation.
	if _, err := db.Collection("answer_log").Indexes().CreateMany(ctx, []mongo.IndexModel{
		{
			Keys:    bson.D{{Key: "userId", Value: 1}, {Key: "createdAt", Value: -1}},
			Options: options.Index().SetName("idx_user_recent"),
		},
		{
			Keys:    bson.D{{Key: "userId", Value: 1}, {Key: "topic", Value: 1}},
			Options: options.Index().SetName("idx_user_topic"),
		},
	}); err != nil {
		log.Fatal(ctx, "answer_log indexes failed", "err", err)
	}
	log.FromContext(ctx).Info("answer_log indexes ensured")

	// §4.5 Deeper analytics — rating_history is one row per (user × match),
	// recording the rating snapshot AFTER the post-match Elo update. The
	// (userId, createdAt asc) index is the rating-graph read path: pull
	// the last 30 days oldest-first, then bucket by UTC day in Go.
	if _, err := db.Collection("rating_history").Indexes().CreateOne(ctx, mongo.IndexModel{
		Keys:    bson.D{{Key: "userId", Value: 1}, {Key: "createdAt", Value: 1}},
		Options: options.Index().SetName("idx_user_chronological"),
	}); err != nil {
		log.Fatal(ctx, "rating_history index failed", "err", err)
	}
	log.FromContext(ctx).Info("rating_history index ensured")

	log.FromContext(ctx).Info("indexes created")

	// --- Seed questions ---
	data, err := os.ReadFile("questions.json")
	if err != nil {
		// Try alternate path (when run from project root)
		data, err = os.ReadFile("seed/questions.json")
		if err != nil {
			log.Fatal(ctx, "read questions.json failed", "err", err)
		}
	}

	var questions []Question
	if err := json.Unmarshal(data, &questions); err != nil {
		log.Fatal(ctx, "parse questions.json failed", "err", err)
	}

	// Upsert questions to avoid duplicates on re-run
	for i, q := range questions {
		filter := bson.M{"text": q.Text}
		update := bson.M{"$setOnInsert": q}
		_, err := questionsColl.UpdateOne(ctx, filter, update, options.UpdateOne().SetUpsert(true))
		if err != nil {
			log.FromContext(ctx).Error("question upsert failed", "index", i, "err", err)
		}
	}
	count, _ := questionsColl.CountDocuments(ctx, bson.M{})
	log.FromContext(ctx).Info("questions in database", "count", count)

	// --- Seed test users ---
	testUsers := []struct {
		Username string
		Password string
		Rating   int32
		Wins     int32
		Played   int32
	}{
		{"alice", "testpass123", 1400, 15, 20},
		{"bob", "testpass123", 1250, 8, 18},
		{"charlie", "testpass123", 1100, 5, 15},
		{"diana", "testpass123", 1350, 12, 22},
		{"eve", "testpass123", 950, 3, 12},
		{"frank", "testpass123", 1500, 20, 25},
	}

	for _, u := range testUsers {
		hash, _ := bcrypt.GenerateFromPassword([]byte(u.Password), bcrypt.DefaultCost)
		id := fmt.Sprintf("user_%s", u.Username)
		nameSlice := u.Username
		if len(nameSlice) > 4 {
			nameSlice = nameSlice[:4]
		}
		refCode := fmt.Sprintf("REF%s", nameSlice)
		doc := bson.M{
			"_id":                 id,
			"username":            u.Username,
			"passwordHash":        string(hash),
			"isGuest":             false,
			"rating":              u.Rating,
			"matchesPlayed":       u.Played,
			"wins":                u.Wins,
			"plan":                "free",
			"coins":               int64(0),
			"referralCode":        refCode,
			"streak":              bson.M{"current": 0, "longest": 0, "lastClaimedDate": ""},
			"onboardingCompleted": true,
			"preferredTopics":     []string{"science", "history", "geography"},
			"createdAt":           time.Now().Unix(),
		}
		_, err := usersColl.UpdateOne(ctx, bson.M{"_id": id}, bson.M{"$setOnInsert": doc}, options.UpdateOne().SetUpsert(true))
		if err != nil {
			log.FromContext(ctx).Error("user upsert failed", "username", u.Username, "err", err)
		}
	}
	userCount, _ := usersColl.CountDocuments(ctx, bson.M{})
	log.FromContext(ctx).Info("users in database", "count", userCount)

	// One-shot migration for existing users that pre-date the onboarding flag.
	// Anyone with matchesPlayed > 0 has implicitly "onboarded" — mark them
	// so they don't get thrown into the onboarding flow on next app open.
	migRes, err := usersColl.UpdateMany(ctx,
		bson.M{
			"onboardingCompleted": bson.M{"$exists": false},
			"matchesPlayed":       bson.M{"$gt": 0},
		},
		bson.M{"$set": bson.M{"onboardingCompleted": true}},
	)
	if err == nil && migRes.ModifiedCount > 0 {
		log.FromContext(ctx).Info("migrated existing users to onboardingCompleted=true", "count", migRes.ModifiedCount)
	}

	// §4.3 (PR 4) backfill: pre-shop users have no inventory fields. Seed
	// rerollCharges=0 / streakFreezeHeld=false / streakFreezeWeekISO="" so
	// the GetShopInventory RPC and Purchase.Buy weekly-cap predicate never
	// have to special-case "field absent" vs "field zero".
	shopBackfillRes, err := usersColl.UpdateMany(ctx,
		bson.M{"rerollCharges": bson.M{"$exists": false}},
		bson.M{"$set": bson.M{
			"rerollCharges":       int32(0),
			"streakFreezeHeld":    false,
			"streakFreezeWeekISO": "",
		}},
	)
	if err != nil {
		log.Fatal(ctx, "shop field backfill failed", "err", err)
	}
	log.FromContext(ctx).Info("shop fields backfilled", "count", shopBackfillRes.ModifiedCount)

	// --- Seed tournaments ---
	// Each tournament is inserted with a string _id (hex ObjectID). Without
	// it, Mongo auto-assigns a binary primitive.ObjectID which then breaks
	// the typed-struct decode (ID string) in GetTournamentList /
	// GetTournament and confuses JoinTournament's string-keyed _id lookup.
	// Existing dev databases keep their binary _ids — drop the tournaments
	// collection and re-run seed to repair them.
	tournamentsColl := db.Collection("tournaments")
	now := time.Now()
	tournaments := []bson.M{
		{
			"_id":              bson.NewObjectID().Hex(),
			"name":             "Weekend Warriors",
			"startTime":        now.Add(2 * 24 * time.Hour),
			"endTime":          now.Add(3 * 24 * time.Hour),
			"entryDeadline":    now.Add(2 * 24 * time.Hour),
			"status":           "upcoming",
			"participants":     bson.A{},
			"requiredPlan":     "premium",
			"prizeDescription": "Top 3 win 500 / 300 / 100 coins",
			"prizePool":        bson.A{int64(500), int64(300), int64(100)},
			"winnersAwarded":   false,
			"reminderSent":     false,
			"createdAt":        now,
		},
		{
			"_id":              bson.NewObjectID().Hex(),
			"name":             "Open Challenge",
			"startTime":        now.Add(5 * 24 * time.Hour),
			"endTime":          now.Add(6 * 24 * time.Hour),
			"entryDeadline":    now.Add(5 * 24 * time.Hour),
			"status":           "upcoming",
			"participants":     bson.A{},
			"requiredPlan":     "free",
			"prizeDescription": "Open to all — Top 3 win 200 / 100 / 50 coins",
			"prizePool":        bson.A{int64(200), int64(100), int64(50)},
			"winnersAwarded":   false,
			"reminderSent":     false,
			"createdAt":        now,
		},
		// Phase 3 (4.2): a tournament that is *currently active* in dev so
		// devs can play a match and immediately observe standings filling
		// in via the scoring service's tournament_standings updater. Ends
		// 6 hours from seed time so a normal dev session doesn't outlast it.
		{
			"_id":              bson.NewObjectID().Hex(),
			"name":             "Live Dev Sprint",
			"startTime":        now.Add(-1 * time.Minute),
			"endTime":          now.Add(6 * time.Hour),
			"entryDeadline":    now.Add(30 * time.Minute),
			"status":           "active",
			"participants":     bson.A{},
			"requiredPlan":     "free",
			"prizeDescription": "Live test tournament — Top 3 win 300 / 150 / 50 coins",
			"prizePool":        bson.A{int64(300), int64(150), int64(50)},
			"winnersAwarded":   false,
			"reminderSent":     false,
			"createdAt":        now,
		},
	}
	for _, t := range tournaments {
		tournamentsColl.UpdateOne(ctx,
			bson.M{"name": t["name"]},
			bson.M{"$setOnInsert": t},
			options.UpdateOne().SetUpsert(true),
		)
	}
	tCount, _ := tournamentsColl.CountDocuments(ctx, bson.M{})
	log.FromContext(ctx).Info("tournaments in database", "count", tCount)

	// PR 4 (§4.3): upsert shop catalog from JSON. We try the in-image path
	// first (the Dockerfile copies seed/shop_items.json to /data) and fall
	// back to the repo-relative path for local `go run ./seed` invocations.
	shopPath := "/data/shop_items.json"
	if _, err := os.Stat(shopPath); err != nil {
		shopPath = "seed/shop_items.json"
		if _, err := os.Stat(shopPath); err != nil {
			shopPath = "shop_items.json"
		}
	}
	items, err := shop.LoadFromFile(shopPath)
	if err != nil {
		log.Fatal(ctx, "load shop items failed", "path", shopPath, "err", err)
	}
	if err := shop.Upsert(ctx, db, items); err != nil {
		log.Fatal(ctx, "upsert shop items failed", "err", err)
	}
	log.FromContext(ctx).Info("upserted shop items", "count", len(items))

	log.FromContext(ctx).Info("done")
}
