package main

import (
	"context"
	"encoding/json"
	"fmt"
	"log"
	"os"
	"time"

	"go.mongodb.org/mongo-driver/v2/bson"
	"go.mongodb.org/mongo-driver/v2/mongo"
	"go.mongodb.org/mongo-driver/v2/mongo/options"
	"golang.org/x/crypto/bcrypt"

	"quiz-battle/pkg/coins"
	"quiz-battle/pkg/coins/shop"
)

type Question struct {
	Text              string   `json:"text" bson:"text"`
	Options           []string `json:"options" bson:"options"`
	CorrectIndex      int      `json:"correctIndex" bson:"correctIndex"`
	Difficulty        string   `json:"difficulty" bson:"difficulty"`
	Topic             string   `json:"topic" bson:"topic"`
	AvgResponseTimeMs int      `json:"avgResponseTimeMs" bson:"avgResponseTimeMs"`
}

func main() {
	ctx, cancel := context.WithTimeout(context.Background(), 30*time.Second)
	defer cancel()

	mongoURI := os.Getenv("MONGO_URI")
	if mongoURI == "" {
		mongoURI = "mongodb://localhost:27017/quizbattle"
	}

	client, err := mongo.Connect(options.Client().ApplyURI(mongoURI))
	if err != nil {
		log.Fatalf("mongo connect: %v", err)
	}
	defer client.Disconnect(ctx)

	db := client.Database(coins.DefaultDBName)

	// --- Create indexes ---
	log.Println("[seed] creating indexes...")

	usersColl := db.Collection("users")
	usersColl.Indexes().CreateOne(ctx, mongo.IndexModel{
		Keys:    bson.D{{Key: "username", Value: 1}},
		Options: options.Index().SetUnique(true),
	})
	usersColl.Indexes().CreateOne(ctx, mongo.IndexModel{
		Keys:    bson.D{{Key: "email", Value: 1}},
		Options: options.Index().SetUnique(true).SetSparse(true),
	})

	questionsColl := db.Collection("questions")
	questionsColl.Indexes().CreateOne(ctx, mongo.IndexModel{
		Keys: bson.D{{Key: "difficulty", Value: 1}},
	})

	db.Collection("match_history").Indexes().CreateOne(ctx, mongo.IndexModel{
		Keys:    bson.D{{Key: "roomId", Value: 1}},
		Options: options.Index().SetUnique(true),
	})
	db.Collection("match_history").Indexes().CreateOne(ctx, mongo.IndexModel{
		Keys: bson.D{{Key: "players.userId", Value: 1}},
	})

	// Phase 2 indexes
	usersColl.Indexes().CreateOne(ctx, mongo.IndexModel{
		Keys:    bson.D{{Key: "googleId", Value: 1}},
		Options: options.Index().SetUnique(true).SetSparse(true),
	})
	usersColl.Indexes().CreateOne(ctx, mongo.IndexModel{
		Keys:    bson.D{{Key: "referralCode", Value: 1}},
		Options: options.Index().SetUnique(true).SetSparse(true),
	})
	usersColl.Indexes().CreateOne(ctx, mongo.IndexModel{
		Keys: bson.D{{Key: "plan", Value: 1}, {Key: "planExpiresAt", Value: 1}},
	})

	paymentsColl := db.Collection("payments")
	paymentsColl.Indexes().CreateOne(ctx, mongo.IndexModel{
		Keys:    bson.D{{Key: "razorpayOrderId", Value: 1}},
		Options: options.Index().SetUnique(true),
	})
	paymentsColl.Indexes().CreateOne(ctx, mongo.IndexModel{
		Keys: bson.D{{Key: "userId", Value: 1}},
	})

	referralsColl := db.Collection("referrals")
	referralsColl.Indexes().CreateOne(ctx, mongo.IndexModel{
		Keys:    bson.D{{Key: "refereeId", Value: 1}},
		Options: options.Index().SetUnique(true),
	})
	referralsColl.Indexes().CreateOne(ctx, mongo.IndexModel{
		Keys: bson.D{{Key: "referrerId", Value: 1}},
	})

	db.Collection("tournaments").Indexes().CreateOne(ctx, mongo.IndexModel{
		Keys: bson.D{{Key: "startTime", Value: 1}, {Key: "status", Value: 1}},
	})
	// Phase 3 (4.2): the weekly auto-creation cron upserts on
	// (autoGenerated, weekKey). Sparse + unique gives us idempotency
	// without forbidding manually-seeded tournaments where weekKey is unset.
	db.Collection("tournaments").Indexes().CreateOne(ctx, mongo.IndexModel{
		Keys:    bson.D{{Key: "autoGenerated", Value: 1}, {Key: "weekKey", Value: 1}},
		Options: options.Index().SetUnique(true).SetSparse(true),
	})
	// Finalization-worker filter: status + endTime + winnersAwarded.
	db.Collection("tournaments").Indexes().CreateOne(ctx, mongo.IndexModel{
		Keys: bson.D{{Key: "status", Value: 1}, {Key: "endTime", Value: 1}, {Key: "winnersAwarded", Value: 1}},
	})

	// tournament_standings: per-(tournament, user) singleton + per-tournament ranking lookup.
	standingsColl := db.Collection("tournament_standings")
	standingsColl.Indexes().CreateOne(ctx, mongo.IndexModel{
		Keys:    bson.D{{Key: "tournamentId", Value: 1}, {Key: "userId", Value: 1}},
		Options: options.Index().SetUnique(true),
	})
	standingsColl.Indexes().CreateOne(ctx, mongo.IndexModel{
		// Score descending so the finalization worker's top-N query
		// (sort by score desc, limit N) hits the index leading edge.
		Keys: bson.D{{Key: "tournamentId", Value: 1}, {Key: "score", Value: -1}},
	})

	// tournament_payouts: durable work-list that backs the at-least-once
	// delivery of tournament.finished events. Unique key gives consumer-side
	// dedup; status index lets the drain worker sweep pending rows fast.
	payoutsColl := db.Collection("tournament_payouts")
	payoutsColl.Indexes().CreateOne(ctx, mongo.IndexModel{
		Keys:    bson.D{{Key: "tournamentId", Value: 1}, {Key: "userId", Value: 1}},
		Options: options.Index().SetUnique(true),
	})
	payoutsColl.Indexes().CreateOne(ctx, mongo.IndexModel{
		Keys: bson.D{{Key: "status", Value: 1}},
	})

	// Phase 3 (4.3): coin_ledger is the immutable source of truth for every
	// balance change. The unique compound index on (userId, refId, reason)
	// gives Grant its idempotency: calling Grant twice with the same refId
	// returns the existing row instead of double-crediting. The (userId,
	// createdAt desc) index is the read path for GetLedger pagination.
	ledgerColl := db.Collection("coin_ledger")
	if _, err := ledgerColl.Indexes().CreateMany(ctx, []mongo.IndexModel{
		{
			Keys:    bson.D{{Key: "userId", Value: 1}, {Key: "refId", Value: 1}, {Key: "reason", Value: 1}},
			Options: options.Index().SetUnique(true).SetName("uniq_user_ref_reason"),
		},
		{
			Keys:    bson.D{{Key: "userId", Value: 1}, {Key: "createdAt", Value: -1}},
			Options: options.Index().SetName("idx_user_recent"),
		},
	}); err != nil {
		log.Fatalf("[seed] coin_ledger indexes: %v", err)
	}
	log.Println("[seed] coin_ledger indexes ensured")

	log.Println("[seed] indexes created")

	// --- Seed questions ---
	data, err := os.ReadFile("questions.json")
	if err != nil {
		// Try alternate path (when run from project root)
		data, err = os.ReadFile("seed/questions.json")
		if err != nil {
			log.Fatalf("read questions.json: %v", err)
		}
	}

	var questions []Question
	if err := json.Unmarshal(data, &questions); err != nil {
		log.Fatalf("parse questions.json: %v", err)
	}

	// Upsert questions to avoid duplicates on re-run
	for i, q := range questions {
		filter := bson.M{"text": q.Text}
		update := bson.M{"$setOnInsert": q}
		_, err := questionsColl.UpdateOne(ctx, filter, update, options.UpdateOne().SetUpsert(true))
		if err != nil {
			log.Printf("[seed] question %d upsert error: %v", i, err)
		}
	}
	count, _ := questionsColl.CountDocuments(ctx, bson.M{})
	log.Printf("[seed] %d questions in database", count)

	// --- Seed test users ---
	testUsers := []struct {
		Username string
		Password string
		Rating   int32
		Wins     int32
		Played   int32
	}{
		{"alice", "testpass123", 1400, 15, 20},
		{"bob", "testpass123", 1250, 8, 18},
		{"charlie", "testpass123", 1100, 5, 15},
		{"diana", "testpass123", 1350, 12, 22},
		{"eve", "testpass123", 950, 3, 12},
		{"frank", "testpass123", 1500, 20, 25},
	}

	for _, u := range testUsers {
		hash, _ := bcrypt.GenerateFromPassword([]byte(u.Password), bcrypt.DefaultCost)
		id := fmt.Sprintf("user_%s", u.Username)
		nameSlice := u.Username
		if len(nameSlice) > 4 {
			nameSlice = nameSlice[:4]
		}
		refCode := fmt.Sprintf("REF%s", nameSlice)
		doc := bson.M{
			"_id":                 id,
			"username":            u.Username,
			"passwordHash":        string(hash),
			"isGuest":             false,
			"rating":              u.Rating,
			"matchesPlayed":       u.Played,
			"wins":                u.Wins,
			"plan":                "free",
			"coins":               int64(0),
			"referralCode":        refCode,
			"streak":              bson.M{"current": 0, "longest": 0, "lastClaimedDate": ""},
			"onboardingCompleted": true,
			"preferredTopics":     []string{"science", "history", "geography"},
			"createdAt":           time.Now().Unix(),
		}
		_, err := usersColl.UpdateOne(ctx, bson.M{"_id": id}, bson.M{"$setOnInsert": doc}, options.UpdateOne().SetUpsert(true))
		if err != nil {
			log.Printf("[seed] user %s upsert error: %v", u.Username, err)
		}
	}
	userCount, _ := usersColl.CountDocuments(ctx, bson.M{})
	log.Printf("[seed] %d users in database", userCount)

	// One-shot migration for existing users that pre-date the onboarding flag.
	// Anyone with matchesPlayed > 0 has implicitly "onboarded" — mark them
	// so they don't get thrown into the onboarding flow on next app open.
	migRes, err := usersColl.UpdateMany(ctx,
		bson.M{
			"onboardingCompleted": bson.M{"$exists": false},
			"matchesPlayed":       bson.M{"$gt": 0},
		},
		bson.M{"$set": bson.M{"onboardingCompleted": true}},
	)
	if err == nil && migRes.ModifiedCount > 0 {
		log.Printf("[seed] migrated %d existing users to onboardingCompleted=true", migRes.ModifiedCount)
	}

	// §4.3 (PR 4) backfill: pre-shop users have no inventory fields. Seed
	// rerollCharges=0 / streakFreezeHeld=false / streakFreezeWeekISO="" so
	// the GetShopInventory RPC and Purchase.Buy weekly-cap predicate never
	// have to special-case "field absent" vs "field zero".
	shopBackfillRes, err := usersColl.UpdateMany(ctx,
		bson.M{"rerollCharges": bson.M{"$exists": false}},
		bson.M{"$set": bson.M{
			"rerollCharges":       int32(0),
			"streakFreezeHeld":    false,
			"streakFreezeWeekISO": "",
		}},
	)
	if err != nil {
		log.Fatalf("[seed] shop field backfill: %v", err)
	}
	log.Printf("[seed] shop fields backfilled on %d users", shopBackfillRes.ModifiedCount)

	// --- Seed tournaments ---
	tournamentsColl := db.Collection("tournaments")
	now := time.Now()
	tournaments := []bson.M{
		{
			"name":             "Weekend Warriors",
			"startTime":        now.Add(2 * 24 * time.Hour),
			"endTime":          now.Add(3 * 24 * time.Hour),
			"entryDeadline":    now.Add(2 * 24 * time.Hour),
			"status":           "upcoming",
			"participants":     bson.A{},
			"requiredPlan":     "premium",
			"prizeDescription": "Top 3 win 500 / 300 / 100 coins",
			"prizePool":        bson.A{int64(500), int64(300), int64(100)},
			"winnersAwarded":   false,
			"reminderSent":     false,
			"createdAt":        now,
		},
		{
			"name":             "Open Challenge",
			"startTime":        now.Add(5 * 24 * time.Hour),
			"endTime":          now.Add(6 * 24 * time.Hour),
			"entryDeadline":    now.Add(5 * 24 * time.Hour),
			"status":           "upcoming",
			"participants":     bson.A{},
			"requiredPlan":     "free",
			"prizeDescription": "Open to all — Top 3 win 200 / 100 / 50 coins",
			"prizePool":        bson.A{int64(200), int64(100), int64(50)},
			"winnersAwarded":   false,
			"reminderSent":     false,
			"createdAt":        now,
		},
		// Phase 3 (4.2): a tournament that is *currently active* in dev so
		// devs can play a match and immediately observe standings filling
		// in via the scoring service's tournament_standings updater. Ends
		// 6 hours from seed time so a normal dev session doesn't outlast it.
		{
			"name":             "Live Dev Sprint",
			"startTime":        now.Add(-1 * time.Minute),
			"endTime":          now.Add(6 * time.Hour),
			"entryDeadline":    now.Add(30 * time.Minute),
			"status":           "active",
			"participants":     bson.A{},
			"requiredPlan":     "free",
			"prizeDescription": "Live test tournament — Top 3 win 300 / 150 / 50 coins",
			"prizePool":        bson.A{int64(300), int64(150), int64(50)},
			"winnersAwarded":   false,
			"reminderSent":     false,
			"createdAt":        now,
		},
	}
	for _, t := range tournaments {
		tournamentsColl.UpdateOne(ctx,
			bson.M{"name": t["name"]},
			bson.M{"$setOnInsert": t},
			options.UpdateOne().SetUpsert(true),
		)
	}
	tCount, _ := tournamentsColl.CountDocuments(ctx, bson.M{})
	log.Printf("[seed] %d tournaments in database", tCount)

	// PR 4 (§4.3): upsert shop catalog from JSON. We try the in-image path
	// first (the Dockerfile copies seed/shop_items.json to /data) and fall
	// back to the repo-relative path for local `go run ./seed` invocations.
	shopPath := "/data/shop_items.json"
	if _, err := os.Stat(shopPath); err != nil {
		shopPath = "seed/shop_items.json"
		if _, err := os.Stat(shopPath); err != nil {
			shopPath = "shop_items.json"
		}
	}
	items, err := shop.LoadFromFile(shopPath)
	if err != nil {
		log.Fatalf("[seed] load shop items from %s: %v", shopPath, err)
	}
	if err := shop.Upsert(ctx, db, items); err != nil {
		log.Fatalf("[seed] upsert shop items: %v", err)
	}
	log.Printf("[seed] upserted %d shop items", len(items))

	log.Println("[seed] done")
}
