// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v4.25.1
// source: proto/quiz.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	MatchmakingService_JoinMatchmaking_FullMethodName  = "/quiz.MatchmakingService/JoinMatchmaking"
	MatchmakingService_LeaveMatchmaking_FullMethodName = "/quiz.MatchmakingService/LeaveMatchmaking"
	MatchmakingService_SubscribeToMatch_FullMethodName = "/quiz.MatchmakingService/SubscribeToMatch"
)

// MatchmakingServiceClient is the client API for MatchmakingService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type MatchmakingServiceClient interface {
	JoinMatchmaking(ctx context.Context, in *JoinMatchmakingRequest, opts ...grpc.CallOption) (*JoinMatchmakingResponse, error)
	LeaveMatchmaking(ctx context.Context, in *LeaveMatchmakingRequest, opts ...grpc.CallOption) (*LeaveMatchmakingResponse, error)
	SubscribeToMatch(ctx context.Context, in *SubscribeToMatchRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[MatchEvent], error)
}

type matchmakingServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewMatchmakingServiceClient(cc grpc.ClientConnInterface) MatchmakingServiceClient {
	return &matchmakingServiceClient{cc}
}

func (c *matchmakingServiceClient) JoinMatchmaking(ctx context.Context, in *JoinMatchmakingRequest, opts ...grpc.CallOption) (*JoinMatchmakingResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(JoinMatchmakingResponse)
	err := c.cc.Invoke(ctx, MatchmakingService_JoinMatchmaking_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *matchmakingServiceClient) LeaveMatchmaking(ctx context.Context, in *LeaveMatchmakingRequest, opts ...grpc.CallOption) (*LeaveMatchmakingResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LeaveMatchmakingResponse)
	err := c.cc.Invoke(ctx, MatchmakingService_LeaveMatchmaking_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *matchmakingServiceClient) SubscribeToMatch(ctx context.Context, in *SubscribeToMatchRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[MatchEvent], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &MatchmakingService_ServiceDesc.Streams[0], MatchmakingService_SubscribeToMatch_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[SubscribeToMatchRequest, MatchEvent]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type MatchmakingService_SubscribeToMatchClient = grpc.ServerStreamingClient[MatchEvent]

// MatchmakingServiceServer is the server API for MatchmakingService service.
// All implementations must embed UnimplementedMatchmakingServiceServer
// for forward compatibility.
type MatchmakingServiceServer interface {
	JoinMatchmaking(context.Context, *JoinMatchmakingRequest) (*JoinMatchmakingResponse, error)
	LeaveMatchmaking(context.Context, *LeaveMatchmakingRequest) (*LeaveMatchmakingResponse, error)
	SubscribeToMatch(*SubscribeToMatchRequest, grpc.ServerStreamingServer[MatchEvent]) error
	mustEmbedUnimplementedMatchmakingServiceServer()
}

// UnimplementedMatchmakingServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedMatchmakingServiceServer struct{}

func (UnimplementedMatchmakingServiceServer) JoinMatchmaking(context.Context, *JoinMatchmakingRequest) (*JoinMatchmakingResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method JoinMatchmaking not implemented")
}
func (UnimplementedMatchmakingServiceServer) LeaveMatchmaking(context.Context, *LeaveMatchmakingRequest) (*LeaveMatchmakingResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method LeaveMatchmaking not implemented")
}
func (UnimplementedMatchmakingServiceServer) SubscribeToMatch(*SubscribeToMatchRequest, grpc.ServerStreamingServer[MatchEvent]) error {
	return status.Error(codes.Unimplemented, "method SubscribeToMatch not implemented")
}
func (UnimplementedMatchmakingServiceServer) mustEmbedUnimplementedMatchmakingServiceServer() {}
func (UnimplementedMatchmakingServiceServer) testEmbeddedByValue()                            {}

// UnsafeMatchmakingServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MatchmakingServiceServer will
// result in compilation errors.
type UnsafeMatchmakingServiceServer interface {
	mustEmbedUnimplementedMatchmakingServiceServer()
}

func RegisterMatchmakingServiceServer(s grpc.ServiceRegistrar, srv MatchmakingServiceServer) {
	// If the following call panics, it indicates UnimplementedMatchmakingServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&MatchmakingService_ServiceDesc, srv)
}

func _MatchmakingService_JoinMatchmaking_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(JoinMatchmakingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MatchmakingServiceServer).JoinMatchmaking(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MatchmakingService_JoinMatchmaking_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MatchmakingServiceServer).JoinMatchmaking(ctx, req.(*JoinMatchmakingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MatchmakingService_LeaveMatchmaking_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LeaveMatchmakingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MatchmakingServiceServer).LeaveMatchmaking(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MatchmakingService_LeaveMatchmaking_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MatchmakingServiceServer).LeaveMatchmaking(ctx, req.(*LeaveMatchmakingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MatchmakingService_SubscribeToMatch_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(SubscribeToMatchRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(MatchmakingServiceServer).SubscribeToMatch(m, &grpc.GenericServerStream[SubscribeToMatchRequest, MatchEvent]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type MatchmakingService_SubscribeToMatchServer = grpc.ServerStreamingServer[MatchEvent]

// MatchmakingService_ServiceDesc is the grpc.ServiceDesc for MatchmakingService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MatchmakingService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "quiz.MatchmakingService",
	HandlerType: (*MatchmakingServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "JoinMatchmaking",
			Handler:    _MatchmakingService_JoinMatchmaking_Handler,
		},
		{
			MethodName: "LeaveMatchmaking",
			Handler:    _MatchmakingService_LeaveMatchmaking_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "SubscribeToMatch",
			Handler:       _MatchmakingService_SubscribeToMatch_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "proto/quiz.proto",
}

const (
	QuizService_GetRoomQuestions_FullMethodName = "/quiz.QuizService/GetRoomQuestions"
	QuizService_SubmitAnswer_FullMethodName     = "/quiz.QuizService/SubmitAnswer"
	QuizService_StreamGameEvents_FullMethodName = "/quiz.QuizService/StreamGameEvents"
)

// QuizServiceClient is the client API for QuizService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type QuizServiceClient interface {
	GetRoomQuestions(ctx context.Context, in *GetRoomQuestionsRequest, opts ...grpc.CallOption) (*GetRoomQuestionsResponse, error)
	SubmitAnswer(ctx context.Context, in *SubmitAnswerRequest, opts ...grpc.CallOption) (*SubmitAnswerResponse, error)
	StreamGameEvents(ctx context.Context, in *StreamGameEventsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[GameEvent], error)
}

type quizServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewQuizServiceClient(cc grpc.ClientConnInterface) QuizServiceClient {
	return &quizServiceClient{cc}
}

func (c *quizServiceClient) GetRoomQuestions(ctx context.Context, in *GetRoomQuestionsRequest, opts ...grpc.CallOption) (*GetRoomQuestionsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetRoomQuestionsResponse)
	err := c.cc.Invoke(ctx, QuizService_GetRoomQuestions_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *quizServiceClient) SubmitAnswer(ctx context.Context, in *SubmitAnswerRequest, opts ...grpc.CallOption) (*SubmitAnswerResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SubmitAnswerResponse)
	err := c.cc.Invoke(ctx, QuizService_SubmitAnswer_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *quizServiceClient) StreamGameEvents(ctx context.Context, in *StreamGameEventsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[GameEvent], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &QuizService_ServiceDesc.Streams[0], QuizService_StreamGameEvents_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[StreamGameEventsRequest, GameEvent]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type QuizService_StreamGameEventsClient = grpc.ServerStreamingClient[GameEvent]

// QuizServiceServer is the server API for QuizService service.
// All implementations must embed UnimplementedQuizServiceServer
// for forward compatibility.
type QuizServiceServer interface {
	GetRoomQuestions(context.Context, *GetRoomQuestionsRequest) (*GetRoomQuestionsResponse, error)
	SubmitAnswer(context.Context, *SubmitAnswerRequest) (*SubmitAnswerResponse, error)
	StreamGameEvents(*StreamGameEventsRequest, grpc.ServerStreamingServer[GameEvent]) error
	mustEmbedUnimplementedQuizServiceServer()
}

// UnimplementedQuizServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedQuizServiceServer struct{}

func (UnimplementedQuizServiceServer) GetRoomQuestions(context.Context, *GetRoomQuestionsRequest) (*GetRoomQuestionsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetRoomQuestions not implemented")
}
func (UnimplementedQuizServiceServer) SubmitAnswer(context.Context, *SubmitAnswerRequest) (*SubmitAnswerResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SubmitAnswer not implemented")
}
func (UnimplementedQuizServiceServer) StreamGameEvents(*StreamGameEventsRequest, grpc.ServerStreamingServer[GameEvent]) error {
	return status.Error(codes.Unimplemented, "method StreamGameEvents not implemented")
}
func (UnimplementedQuizServiceServer) mustEmbedUnimplementedQuizServiceServer() {}
func (UnimplementedQuizServiceServer) testEmbeddedByValue()                     {}

// UnsafeQuizServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to QuizServiceServer will
// result in compilation errors.
type UnsafeQuizServiceServer interface {
	mustEmbedUnimplementedQuizServiceServer()
}

func RegisterQuizServiceServer(s grpc.ServiceRegistrar, srv QuizServiceServer) {
	// If the following call panics, it indicates UnimplementedQuizServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&QuizService_ServiceDesc, srv)
}

func _QuizService_GetRoomQuestions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRoomQuestionsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QuizServiceServer).GetRoomQuestions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: QuizService_GetRoomQuestions_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QuizServiceServer).GetRoomQuestions(ctx, req.(*GetRoomQuestionsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _QuizService_SubmitAnswer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SubmitAnswerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QuizServiceServer).SubmitAnswer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: QuizService_SubmitAnswer_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QuizServiceServer).SubmitAnswer(ctx, req.(*SubmitAnswerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _QuizService_StreamGameEvents_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(StreamGameEventsRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(QuizServiceServer).StreamGameEvents(m, &grpc.GenericServerStream[StreamGameEventsRequest, GameEvent]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type QuizService_StreamGameEventsServer = grpc.ServerStreamingServer[GameEvent]

// QuizService_ServiceDesc is the grpc.ServiceDesc for QuizService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var QuizService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "quiz.QuizService",
	HandlerType: (*QuizServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetRoomQuestions",
			Handler:    _QuizService_GetRoomQuestions_Handler,
		},
		{
			MethodName: "SubmitAnswer",
			Handler:    _QuizService_SubmitAnswer_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamGameEvents",
			Handler:       _QuizService_StreamGameEvents_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "proto/quiz.proto",
}

const (
	ScoringService_CalculateScore_FullMethodName = "/quiz.ScoringService/CalculateScore"
	ScoringService_GetLeaderboard_FullMethodName = "/quiz.ScoringService/GetLeaderboard"
)

// ScoringServiceClient is the client API for ScoringService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ScoringServiceClient interface {
	CalculateScore(ctx context.Context, in *CalculateScoreRequest, opts ...grpc.CallOption) (*CalculateScoreResponse, error)
	GetLeaderboard(ctx context.Context, in *GetLeaderboardRequest, opts ...grpc.CallOption) (*GetLeaderboardResponse, error)
}

type scoringServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewScoringServiceClient(cc grpc.ClientConnInterface) ScoringServiceClient {
	return &scoringServiceClient{cc}
}

func (c *scoringServiceClient) CalculateScore(ctx context.Context, in *CalculateScoreRequest, opts ...grpc.CallOption) (*CalculateScoreResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CalculateScoreResponse)
	err := c.cc.Invoke(ctx, ScoringService_CalculateScore_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *scoringServiceClient) GetLeaderboard(ctx context.Context, in *GetLeaderboardRequest, opts ...grpc.CallOption) (*GetLeaderboardResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetLeaderboardResponse)
	err := c.cc.Invoke(ctx, ScoringService_GetLeaderboard_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ScoringServiceServer is the server API for ScoringService service.
// All implementations must embed UnimplementedScoringServiceServer
// for forward compatibility.
type ScoringServiceServer interface {
	CalculateScore(context.Context, *CalculateScoreRequest) (*CalculateScoreResponse, error)
	GetLeaderboard(context.Context, *GetLeaderboardRequest) (*GetLeaderboardResponse, error)
	mustEmbedUnimplementedScoringServiceServer()
}

// UnimplementedScoringServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedScoringServiceServer struct{}

func (UnimplementedScoringServiceServer) CalculateScore(context.Context, *CalculateScoreRequest) (*CalculateScoreResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CalculateScore not implemented")
}
func (UnimplementedScoringServiceServer) GetLeaderboard(context.Context, *GetLeaderboardRequest) (*GetLeaderboardResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetLeaderboard not implemented")
}
func (UnimplementedScoringServiceServer) mustEmbedUnimplementedScoringServiceServer() {}
func (UnimplementedScoringServiceServer) testEmbeddedByValue()                        {}

// UnsafeScoringServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ScoringServiceServer will
// result in compilation errors.
type UnsafeScoringServiceServer interface {
	mustEmbedUnimplementedScoringServiceServer()
}

func RegisterScoringServiceServer(s grpc.ServiceRegistrar, srv ScoringServiceServer) {
	// If the following call panics, it indicates UnimplementedScoringServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ScoringService_ServiceDesc, srv)
}

func _ScoringService_CalculateScore_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CalculateScoreRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ScoringServiceServer).CalculateScore(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ScoringService_CalculateScore_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ScoringServiceServer).CalculateScore(ctx, req.(*CalculateScoreRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ScoringService_GetLeaderboard_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetLeaderboardRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ScoringServiceServer).GetLeaderboard(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ScoringService_GetLeaderboard_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ScoringServiceServer).GetLeaderboard(ctx, req.(*GetLeaderboardRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ScoringService_ServiceDesc is the grpc.ServiceDesc for ScoringService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ScoringService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "quiz.ScoringService",
	HandlerType: (*ScoringServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CalculateScore",
			Handler:    _ScoringService_CalculateScore_Handler,
		},
		{
			MethodName: "GetLeaderboard",
			Handler:    _ScoringService_GetLeaderboard_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/quiz.proto",
}
