// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v7.34.1
// source: quiz.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	MatchmakingService_JoinMatchmaking_FullMethodName  = "/quiz.MatchmakingService/JoinMatchmaking"
	MatchmakingService_LeaveMatchmaking_FullMethodName = "/quiz.MatchmakingService/LeaveMatchmaking"
	MatchmakingService_SubscribeToMatch_FullMethodName = "/quiz.MatchmakingService/SubscribeToMatch"
)

// MatchmakingServiceClient is the client API for MatchmakingService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type MatchmakingServiceClient interface {
	JoinMatchmaking(ctx context.Context, in *JoinMatchmakingRequest, opts ...grpc.CallOption) (*JoinMatchmakingResponse, error)
	LeaveMatchmaking(ctx context.Context, in *LeaveMatchmakingRequest, opts ...grpc.CallOption) (*LeaveMatchmakingResponse, error)
	SubscribeToMatch(ctx context.Context, in *SubscribeToMatchRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[MatchEvent], error)
}

type matchmakingServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewMatchmakingServiceClient(cc grpc.ClientConnInterface) MatchmakingServiceClient {
	return &matchmakingServiceClient{cc}
}

func (c *matchmakingServiceClient) JoinMatchmaking(ctx context.Context, in *JoinMatchmakingRequest, opts ...grpc.CallOption) (*JoinMatchmakingResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(JoinMatchmakingResponse)
	err := c.cc.Invoke(ctx, MatchmakingService_JoinMatchmaking_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *matchmakingServiceClient) LeaveMatchmaking(ctx context.Context, in *LeaveMatchmakingRequest, opts ...grpc.CallOption) (*LeaveMatchmakingResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LeaveMatchmakingResponse)
	err := c.cc.Invoke(ctx, MatchmakingService_LeaveMatchmaking_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *matchmakingServiceClient) SubscribeToMatch(ctx context.Context, in *SubscribeToMatchRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[MatchEvent], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &MatchmakingService_ServiceDesc.Streams[0], MatchmakingService_SubscribeToMatch_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[SubscribeToMatchRequest, MatchEvent]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type MatchmakingService_SubscribeToMatchClient = grpc.ServerStreamingClient[MatchEvent]

// MatchmakingServiceServer is the server API for MatchmakingService service.
// All implementations must embed UnimplementedMatchmakingServiceServer
// for forward compatibility.
type MatchmakingServiceServer interface {
	JoinMatchmaking(context.Context, *JoinMatchmakingRequest) (*JoinMatchmakingResponse, error)
	LeaveMatchmaking(context.Context, *LeaveMatchmakingRequest) (*LeaveMatchmakingResponse, error)
	SubscribeToMatch(*SubscribeToMatchRequest, grpc.ServerStreamingServer[MatchEvent]) error
	mustEmbedUnimplementedMatchmakingServiceServer()
}

// UnimplementedMatchmakingServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedMatchmakingServiceServer struct{}

func (UnimplementedMatchmakingServiceServer) JoinMatchmaking(context.Context, *JoinMatchmakingRequest) (*JoinMatchmakingResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method JoinMatchmaking not implemented")
}
func (UnimplementedMatchmakingServiceServer) LeaveMatchmaking(context.Context, *LeaveMatchmakingRequest) (*LeaveMatchmakingResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method LeaveMatchmaking not implemented")
}
func (UnimplementedMatchmakingServiceServer) SubscribeToMatch(*SubscribeToMatchRequest, grpc.ServerStreamingServer[MatchEvent]) error {
	return status.Error(codes.Unimplemented, "method SubscribeToMatch not implemented")
}
func (UnimplementedMatchmakingServiceServer) mustEmbedUnimplementedMatchmakingServiceServer() {}
func (UnimplementedMatchmakingServiceServer) testEmbeddedByValue()                            {}

// UnsafeMatchmakingServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MatchmakingServiceServer will
// result in compilation errors.
type UnsafeMatchmakingServiceServer interface {
	mustEmbedUnimplementedMatchmakingServiceServer()
}

func RegisterMatchmakingServiceServer(s grpc.ServiceRegistrar, srv MatchmakingServiceServer) {
	// If the following call panics, it indicates UnimplementedMatchmakingServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&MatchmakingService_ServiceDesc, srv)
}

func _MatchmakingService_JoinMatchmaking_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(JoinMatchmakingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MatchmakingServiceServer).JoinMatchmaking(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MatchmakingService_JoinMatchmaking_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MatchmakingServiceServer).JoinMatchmaking(ctx, req.(*JoinMatchmakingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MatchmakingService_LeaveMatchmaking_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LeaveMatchmakingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MatchmakingServiceServer).LeaveMatchmaking(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MatchmakingService_LeaveMatchmaking_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MatchmakingServiceServer).LeaveMatchmaking(ctx, req.(*LeaveMatchmakingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MatchmakingService_SubscribeToMatch_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(SubscribeToMatchRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(MatchmakingServiceServer).SubscribeToMatch(m, &grpc.GenericServerStream[SubscribeToMatchRequest, MatchEvent]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type MatchmakingService_SubscribeToMatchServer = grpc.ServerStreamingServer[MatchEvent]

// MatchmakingService_ServiceDesc is the grpc.ServiceDesc for MatchmakingService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MatchmakingService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "quiz.MatchmakingService",
	HandlerType: (*MatchmakingServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "JoinMatchmaking",
			Handler:    _MatchmakingService_JoinMatchmaking_Handler,
		},
		{
			MethodName: "LeaveMatchmaking",
			Handler:    _MatchmakingService_LeaveMatchmaking_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "SubscribeToMatch",
			Handler:       _MatchmakingService_SubscribeToMatch_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "quiz.proto",
}

const (
	QuizService_GetRoomQuestions_FullMethodName  = "/quiz.QuizService/GetRoomQuestions"
	QuizService_SubmitAnswer_FullMethodName      = "/quiz.QuizService/SubmitAnswer"
	QuizService_StreamGameEvents_FullMethodName  = "/quiz.QuizService/StreamGameEvents"
	QuizService_GetTournamentList_FullMethodName = "/quiz.QuizService/GetTournamentList"
	QuizService_JoinTournament_FullMethodName    = "/quiz.QuizService/JoinTournament"
)

// QuizServiceClient is the client API for QuizService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type QuizServiceClient interface {
	GetRoomQuestions(ctx context.Context, in *GetRoomQuestionsRequest, opts ...grpc.CallOption) (*GetRoomQuestionsResponse, error)
	SubmitAnswer(ctx context.Context, in *SubmitAnswerRequest, opts ...grpc.CallOption) (*SubmitAnswerResponse, error)
	StreamGameEvents(ctx context.Context, in *StreamGameEventsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[GameEvent], error)
	// Phase 2
	GetTournamentList(ctx context.Context, in *GetTournamentListRequest, opts ...grpc.CallOption) (*GetTournamentListResponse, error)
	JoinTournament(ctx context.Context, in *JoinTournamentRequest, opts ...grpc.CallOption) (*JoinTournamentResponse, error)
}

type quizServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewQuizServiceClient(cc grpc.ClientConnInterface) QuizServiceClient {
	return &quizServiceClient{cc}
}

func (c *quizServiceClient) GetRoomQuestions(ctx context.Context, in *GetRoomQuestionsRequest, opts ...grpc.CallOption) (*GetRoomQuestionsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetRoomQuestionsResponse)
	err := c.cc.Invoke(ctx, QuizService_GetRoomQuestions_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *quizServiceClient) SubmitAnswer(ctx context.Context, in *SubmitAnswerRequest, opts ...grpc.CallOption) (*SubmitAnswerResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SubmitAnswerResponse)
	err := c.cc.Invoke(ctx, QuizService_SubmitAnswer_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *quizServiceClient) StreamGameEvents(ctx context.Context, in *StreamGameEventsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[GameEvent], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &QuizService_ServiceDesc.Streams[0], QuizService_StreamGameEvents_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[StreamGameEventsRequest, GameEvent]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type QuizService_StreamGameEventsClient = grpc.ServerStreamingClient[GameEvent]

func (c *quizServiceClient) GetTournamentList(ctx context.Context, in *GetTournamentListRequest, opts ...grpc.CallOption) (*GetTournamentListResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetTournamentListResponse)
	err := c.cc.Invoke(ctx, QuizService_GetTournamentList_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *quizServiceClient) JoinTournament(ctx context.Context, in *JoinTournamentRequest, opts ...grpc.CallOption) (*JoinTournamentResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(JoinTournamentResponse)
	err := c.cc.Invoke(ctx, QuizService_JoinTournament_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// QuizServiceServer is the server API for QuizService service.
// All implementations must embed UnimplementedQuizServiceServer
// for forward compatibility.
type QuizServiceServer interface {
	GetRoomQuestions(context.Context, *GetRoomQuestionsRequest) (*GetRoomQuestionsResponse, error)
	SubmitAnswer(context.Context, *SubmitAnswerRequest) (*SubmitAnswerResponse, error)
	StreamGameEvents(*StreamGameEventsRequest, grpc.ServerStreamingServer[GameEvent]) error
	// Phase 2
	GetTournamentList(context.Context, *GetTournamentListRequest) (*GetTournamentListResponse, error)
	JoinTournament(context.Context, *JoinTournamentRequest) (*JoinTournamentResponse, error)
	mustEmbedUnimplementedQuizServiceServer()
}

// UnimplementedQuizServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedQuizServiceServer struct{}

func (UnimplementedQuizServiceServer) GetRoomQuestions(context.Context, *GetRoomQuestionsRequest) (*GetRoomQuestionsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetRoomQuestions not implemented")
}
func (UnimplementedQuizServiceServer) SubmitAnswer(context.Context, *SubmitAnswerRequest) (*SubmitAnswerResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SubmitAnswer not implemented")
}
func (UnimplementedQuizServiceServer) StreamGameEvents(*StreamGameEventsRequest, grpc.ServerStreamingServer[GameEvent]) error {
	return status.Error(codes.Unimplemented, "method StreamGameEvents not implemented")
}
func (UnimplementedQuizServiceServer) GetTournamentList(context.Context, *GetTournamentListRequest) (*GetTournamentListResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetTournamentList not implemented")
}
func (UnimplementedQuizServiceServer) JoinTournament(context.Context, *JoinTournamentRequest) (*JoinTournamentResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method JoinTournament not implemented")
}
func (UnimplementedQuizServiceServer) mustEmbedUnimplementedQuizServiceServer() {}
func (UnimplementedQuizServiceServer) testEmbeddedByValue()                     {}

// UnsafeQuizServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to QuizServiceServer will
// result in compilation errors.
type UnsafeQuizServiceServer interface {
	mustEmbedUnimplementedQuizServiceServer()
}

func RegisterQuizServiceServer(s grpc.ServiceRegistrar, srv QuizServiceServer) {
	// If the following call panics, it indicates UnimplementedQuizServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&QuizService_ServiceDesc, srv)
}

func _QuizService_GetRoomQuestions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRoomQuestionsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QuizServiceServer).GetRoomQuestions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: QuizService_GetRoomQuestions_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QuizServiceServer).GetRoomQuestions(ctx, req.(*GetRoomQuestionsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _QuizService_SubmitAnswer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SubmitAnswerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QuizServiceServer).SubmitAnswer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: QuizService_SubmitAnswer_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QuizServiceServer).SubmitAnswer(ctx, req.(*SubmitAnswerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _QuizService_StreamGameEvents_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(StreamGameEventsRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(QuizServiceServer).StreamGameEvents(m, &grpc.GenericServerStream[StreamGameEventsRequest, GameEvent]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type QuizService_StreamGameEventsServer = grpc.ServerStreamingServer[GameEvent]

func _QuizService_GetTournamentList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTournamentListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QuizServiceServer).GetTournamentList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: QuizService_GetTournamentList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QuizServiceServer).GetTournamentList(ctx, req.(*GetTournamentListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _QuizService_JoinTournament_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(JoinTournamentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QuizServiceServer).JoinTournament(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: QuizService_JoinTournament_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QuizServiceServer).JoinTournament(ctx, req.(*JoinTournamentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// QuizService_ServiceDesc is the grpc.ServiceDesc for QuizService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var QuizService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "quiz.QuizService",
	HandlerType: (*QuizServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetRoomQuestions",
			Handler:    _QuizService_GetRoomQuestions_Handler,
		},
		{
			MethodName: "SubmitAnswer",
			Handler:    _QuizService_SubmitAnswer_Handler,
		},
		{
			MethodName: "GetTournamentList",
			Handler:    _QuizService_GetTournamentList_Handler,
		},
		{
			MethodName: "JoinTournament",
			Handler:    _QuizService_JoinTournament_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamGameEvents",
			Handler:       _QuizService_StreamGameEvents_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "quiz.proto",
}

const (
	ScoringService_CalculateScore_FullMethodName       = "/quiz.ScoringService/CalculateScore"
	ScoringService_GetLeaderboard_FullMethodName       = "/quiz.ScoringService/GetLeaderboard"
	ScoringService_GetMatchHistory_FullMethodName      = "/quiz.ScoringService/GetMatchHistory"
	ScoringService_GetHomeScreenData_FullMethodName    = "/quiz.ScoringService/GetHomeScreenData"
	ScoringService_GetReferralDashboard_FullMethodName = "/quiz.ScoringService/GetReferralDashboard"
	ScoringService_ApplyReferralCode_FullMethodName    = "/quiz.ScoringService/ApplyReferralCode"
	ScoringService_UpdateFCMToken_FullMethodName       = "/quiz.ScoringService/UpdateFCMToken"
	ScoringService_GetGlobalLeaderboard_FullMethodName = "/quiz.ScoringService/GetGlobalLeaderboard"
	ScoringService_GetCoinBalance_FullMethodName       = "/quiz.ScoringService/GetCoinBalance"
	ScoringService_GetCoinLedger_FullMethodName        = "/quiz.ScoringService/GetCoinLedger"
)

// ScoringServiceClient is the client API for ScoringService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ScoringServiceClient interface {
	CalculateScore(ctx context.Context, in *CalculateScoreRequest, opts ...grpc.CallOption) (*CalculateScoreResponse, error)
	GetLeaderboard(ctx context.Context, in *GetLeaderboardRequest, opts ...grpc.CallOption) (*GetLeaderboardResponse, error)
	GetMatchHistory(ctx context.Context, in *GetMatchHistoryRequest, opts ...grpc.CallOption) (*GetMatchHistoryResponse, error)
	// Phase 2: User Service RPCs (scoring service acts as user service)
	GetHomeScreenData(ctx context.Context, in *GetHomeScreenDataRequest, opts ...grpc.CallOption) (*GetHomeScreenDataResponse, error)
	GetReferralDashboard(ctx context.Context, in *GetReferralDashboardRequest, opts ...grpc.CallOption) (*GetReferralDashboardResponse, error)
	ApplyReferralCode(ctx context.Context, in *ApplyReferralCodeRequest, opts ...grpc.CallOption) (*ApplyReferralCodeResponse, error)
	UpdateFCMToken(ctx context.Context, in *UpdateFCMTokenRequest, opts ...grpc.CallOption) (*UpdateFCMTokenResponse, error)
	// Phase 3: Global leaderboard with time filters
	GetGlobalLeaderboard(ctx context.Context, in *GetGlobalLeaderboardRequest, opts ...grpc.CallOption) (*GetGlobalLeaderboardResponse, error)
	// Phase 3 (4.3): Coin balance + ledger history. Balance is read from
	// users.coins; ledger reads from coin_ledger via the unique
	// (userId, refId, reason) idempotency index.
	GetCoinBalance(ctx context.Context, in *GetCoinBalanceRequest, opts ...grpc.CallOption) (*GetCoinBalanceResponse, error)
	GetCoinLedger(ctx context.Context, in *GetCoinLedgerRequest, opts ...grpc.CallOption) (*GetCoinLedgerResponse, error)
}

type scoringServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewScoringServiceClient(cc grpc.ClientConnInterface) ScoringServiceClient {
	return &scoringServiceClient{cc}
}

func (c *scoringServiceClient) CalculateScore(ctx context.Context, in *CalculateScoreRequest, opts ...grpc.CallOption) (*CalculateScoreResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CalculateScoreResponse)
	err := c.cc.Invoke(ctx, ScoringService_CalculateScore_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *scoringServiceClient) GetLeaderboard(ctx context.Context, in *GetLeaderboardRequest, opts ...grpc.CallOption) (*GetLeaderboardResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetLeaderboardResponse)
	err := c.cc.Invoke(ctx, ScoringService_GetLeaderboard_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *scoringServiceClient) GetMatchHistory(ctx context.Context, in *GetMatchHistoryRequest, opts ...grpc.CallOption) (*GetMatchHistoryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetMatchHistoryResponse)
	err := c.cc.Invoke(ctx, ScoringService_GetMatchHistory_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *scoringServiceClient) GetHomeScreenData(ctx context.Context, in *GetHomeScreenDataRequest, opts ...grpc.CallOption) (*GetHomeScreenDataResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetHomeScreenDataResponse)
	err := c.cc.Invoke(ctx, ScoringService_GetHomeScreenData_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *scoringServiceClient) GetReferralDashboard(ctx context.Context, in *GetReferralDashboardRequest, opts ...grpc.CallOption) (*GetReferralDashboardResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetReferralDashboardResponse)
	err := c.cc.Invoke(ctx, ScoringService_GetReferralDashboard_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *scoringServiceClient) ApplyReferralCode(ctx context.Context, in *ApplyReferralCodeRequest, opts ...grpc.CallOption) (*ApplyReferralCodeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ApplyReferralCodeResponse)
	err := c.cc.Invoke(ctx, ScoringService_ApplyReferralCode_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *scoringServiceClient) UpdateFCMToken(ctx context.Context, in *UpdateFCMTokenRequest, opts ...grpc.CallOption) (*UpdateFCMTokenResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateFCMTokenResponse)
	err := c.cc.Invoke(ctx, ScoringService_UpdateFCMToken_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *scoringServiceClient) GetGlobalLeaderboard(ctx context.Context, in *GetGlobalLeaderboardRequest, opts ...grpc.CallOption) (*GetGlobalLeaderboardResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetGlobalLeaderboardResponse)
	err := c.cc.Invoke(ctx, ScoringService_GetGlobalLeaderboard_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *scoringServiceClient) GetCoinBalance(ctx context.Context, in *GetCoinBalanceRequest, opts ...grpc.CallOption) (*GetCoinBalanceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetCoinBalanceResponse)
	err := c.cc.Invoke(ctx, ScoringService_GetCoinBalance_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *scoringServiceClient) GetCoinLedger(ctx context.Context, in *GetCoinLedgerRequest, opts ...grpc.CallOption) (*GetCoinLedgerResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetCoinLedgerResponse)
	err := c.cc.Invoke(ctx, ScoringService_GetCoinLedger_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ScoringServiceServer is the server API for ScoringService service.
// All implementations must embed UnimplementedScoringServiceServer
// for forward compatibility.
type ScoringServiceServer interface {
	CalculateScore(context.Context, *CalculateScoreRequest) (*CalculateScoreResponse, error)
	GetLeaderboard(context.Context, *GetLeaderboardRequest) (*GetLeaderboardResponse, error)
	GetMatchHistory(context.Context, *GetMatchHistoryRequest) (*GetMatchHistoryResponse, error)
	// Phase 2: User Service RPCs (scoring service acts as user service)
	GetHomeScreenData(context.Context, *GetHomeScreenDataRequest) (*GetHomeScreenDataResponse, error)
	GetReferralDashboard(context.Context, *GetReferralDashboardRequest) (*GetReferralDashboardResponse, error)
	ApplyReferralCode(context.Context, *ApplyReferralCodeRequest) (*ApplyReferralCodeResponse, error)
	UpdateFCMToken(context.Context, *UpdateFCMTokenRequest) (*UpdateFCMTokenResponse, error)
	// Phase 3: Global leaderboard with time filters
	GetGlobalLeaderboard(context.Context, *GetGlobalLeaderboardRequest) (*GetGlobalLeaderboardResponse, error)
	// Phase 3 (4.3): Coin balance + ledger history. Balance is read from
	// users.coins; ledger reads from coin_ledger via the unique
	// (userId, refId, reason) idempotency index.
	GetCoinBalance(context.Context, *GetCoinBalanceRequest) (*GetCoinBalanceResponse, error)
	GetCoinLedger(context.Context, *GetCoinLedgerRequest) (*GetCoinLedgerResponse, error)
	mustEmbedUnimplementedScoringServiceServer()
}

// UnimplementedScoringServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedScoringServiceServer struct{}

func (UnimplementedScoringServiceServer) CalculateScore(context.Context, *CalculateScoreRequest) (*CalculateScoreResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CalculateScore not implemented")
}
func (UnimplementedScoringServiceServer) GetLeaderboard(context.Context, *GetLeaderboardRequest) (*GetLeaderboardResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetLeaderboard not implemented")
}
func (UnimplementedScoringServiceServer) GetMatchHistory(context.Context, *GetMatchHistoryRequest) (*GetMatchHistoryResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetMatchHistory not implemented")
}
func (UnimplementedScoringServiceServer) GetHomeScreenData(context.Context, *GetHomeScreenDataRequest) (*GetHomeScreenDataResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetHomeScreenData not implemented")
}
func (UnimplementedScoringServiceServer) GetReferralDashboard(context.Context, *GetReferralDashboardRequest) (*GetReferralDashboardResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetReferralDashboard not implemented")
}
func (UnimplementedScoringServiceServer) ApplyReferralCode(context.Context, *ApplyReferralCodeRequest) (*ApplyReferralCodeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ApplyReferralCode not implemented")
}
func (UnimplementedScoringServiceServer) UpdateFCMToken(context.Context, *UpdateFCMTokenRequest) (*UpdateFCMTokenResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateFCMToken not implemented")
}
func (UnimplementedScoringServiceServer) GetGlobalLeaderboard(context.Context, *GetGlobalLeaderboardRequest) (*GetGlobalLeaderboardResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetGlobalLeaderboard not implemented")
}
func (UnimplementedScoringServiceServer) GetCoinBalance(context.Context, *GetCoinBalanceRequest) (*GetCoinBalanceResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetCoinBalance not implemented")
}
func (UnimplementedScoringServiceServer) GetCoinLedger(context.Context, *GetCoinLedgerRequest) (*GetCoinLedgerResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetCoinLedger not implemented")
}
func (UnimplementedScoringServiceServer) mustEmbedUnimplementedScoringServiceServer() {}
func (UnimplementedScoringServiceServer) testEmbeddedByValue()                        {}

// UnsafeScoringServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ScoringServiceServer will
// result in compilation errors.
type UnsafeScoringServiceServer interface {
	mustEmbedUnimplementedScoringServiceServer()
}

func RegisterScoringServiceServer(s grpc.ServiceRegistrar, srv ScoringServiceServer) {
	// If the following call panics, it indicates UnimplementedScoringServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ScoringService_ServiceDesc, srv)
}

func _ScoringService_CalculateScore_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CalculateScoreRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ScoringServiceServer).CalculateScore(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ScoringService_CalculateScore_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ScoringServiceServer).CalculateScore(ctx, req.(*CalculateScoreRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ScoringService_GetLeaderboard_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetLeaderboardRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ScoringServiceServer).GetLeaderboard(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ScoringService_GetLeaderboard_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ScoringServiceServer).GetLeaderboard(ctx, req.(*GetLeaderboardRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ScoringService_GetMatchHistory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetMatchHistoryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ScoringServiceServer).GetMatchHistory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ScoringService_GetMatchHistory_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ScoringServiceServer).GetMatchHistory(ctx, req.(*GetMatchHistoryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ScoringService_GetHomeScreenData_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetHomeScreenDataRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ScoringServiceServer).GetHomeScreenData(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ScoringService_GetHomeScreenData_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ScoringServiceServer).GetHomeScreenData(ctx, req.(*GetHomeScreenDataRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ScoringService_GetReferralDashboard_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetReferralDashboardRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ScoringServiceServer).GetReferralDashboard(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ScoringService_GetReferralDashboard_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ScoringServiceServer).GetReferralDashboard(ctx, req.(*GetReferralDashboardRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ScoringService_ApplyReferralCode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ApplyReferralCodeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ScoringServiceServer).ApplyReferralCode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ScoringService_ApplyReferralCode_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ScoringServiceServer).ApplyReferralCode(ctx, req.(*ApplyReferralCodeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ScoringService_UpdateFCMToken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateFCMTokenRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ScoringServiceServer).UpdateFCMToken(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ScoringService_UpdateFCMToken_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ScoringServiceServer).UpdateFCMToken(ctx, req.(*UpdateFCMTokenRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ScoringService_GetGlobalLeaderboard_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetGlobalLeaderboardRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ScoringServiceServer).GetGlobalLeaderboard(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ScoringService_GetGlobalLeaderboard_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ScoringServiceServer).GetGlobalLeaderboard(ctx, req.(*GetGlobalLeaderboardRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ScoringService_GetCoinBalance_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCoinBalanceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ScoringServiceServer).GetCoinBalance(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ScoringService_GetCoinBalance_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ScoringServiceServer).GetCoinBalance(ctx, req.(*GetCoinBalanceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ScoringService_GetCoinLedger_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCoinLedgerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ScoringServiceServer).GetCoinLedger(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ScoringService_GetCoinLedger_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ScoringServiceServer).GetCoinLedger(ctx, req.(*GetCoinLedgerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ScoringService_ServiceDesc is the grpc.ServiceDesc for ScoringService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ScoringService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "quiz.ScoringService",
	HandlerType: (*ScoringServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CalculateScore",
			Handler:    _ScoringService_CalculateScore_Handler,
		},
		{
			MethodName: "GetLeaderboard",
			Handler:    _ScoringService_GetLeaderboard_Handler,
		},
		{
			MethodName: "GetMatchHistory",
			Handler:    _ScoringService_GetMatchHistory_Handler,
		},
		{
			MethodName: "GetHomeScreenData",
			Handler:    _ScoringService_GetHomeScreenData_Handler,
		},
		{
			MethodName: "GetReferralDashboard",
			Handler:    _ScoringService_GetReferralDashboard_Handler,
		},
		{
			MethodName: "ApplyReferralCode",
			Handler:    _ScoringService_ApplyReferralCode_Handler,
		},
		{
			MethodName: "UpdateFCMToken",
			Handler:    _ScoringService_UpdateFCMToken_Handler,
		},
		{
			MethodName: "GetGlobalLeaderboard",
			Handler:    _ScoringService_GetGlobalLeaderboard_Handler,
		},
		{
			MethodName: "GetCoinBalance",
			Handler:    _ScoringService_GetCoinBalance_Handler,
		},
		{
			MethodName: "GetCoinLedger",
			Handler:    _ScoringService_GetCoinLedger_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "quiz.proto",
}

const (
	AuthService_Register_FullMethodName         = "/quiz.AuthService/Register"
	AuthService_Login_FullMethodName            = "/quiz.AuthService/Login"
	AuthService_GetProfile_FullMethodName       = "/quiz.AuthService/GetProfile"
	AuthService_GuestLogin_FullMethodName       = "/quiz.AuthService/GuestLogin"
	AuthService_LoginWithEmail_FullMethodName   = "/quiz.AuthService/LoginWithEmail"
	AuthService_SendEmailCode_FullMethodName    = "/quiz.AuthService/SendEmailCode"
	AuthService_VerifyEmailCode_FullMethodName  = "/quiz.AuthService/VerifyEmailCode"
	AuthService_LinkEmail_FullMethodName        = "/quiz.AuthService/LinkEmail"
	AuthService_ResetPassword_FullMethodName    = "/quiz.AuthService/ResetPassword"
	AuthService_CheckUsername_FullMethodName    = "/quiz.AuthService/CheckUsername"
	AuthService_DeleteAccount_FullMethodName    = "/quiz.AuthService/DeleteAccount"
	AuthService_GoogleSignIn_FullMethodName     = "/quiz.AuthService/GoogleSignIn"
	AuthService_ClaimDailyReward_FullMethodName = "/quiz.AuthService/ClaimDailyReward"
	AuthService_GetStreakInfo_FullMethodName    = "/quiz.AuthService/GetStreakInfo"
	AuthService_UpdateProfile_FullMethodName    = "/quiz.AuthService/UpdateProfile"
)

// AuthServiceClient is the client API for AuthService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AuthServiceClient interface {
	Register(ctx context.Context, in *RegisterRequest, opts ...grpc.CallOption) (*AuthResponse, error)
	Login(ctx context.Context, in *LoginRequest, opts ...grpc.CallOption) (*AuthResponse, error)
	GetProfile(ctx context.Context, in *GetProfileRequest, opts ...grpc.CallOption) (*ProfileResponse, error)
	GuestLogin(ctx context.Context, in *GuestLoginRequest, opts ...grpc.CallOption) (*AuthResponse, error)
	LoginWithEmail(ctx context.Context, in *EmailLoginRequest, opts ...grpc.CallOption) (*SendEmailCodeResponse, error)
	SendEmailCode(ctx context.Context, in *SendEmailCodeRequest, opts ...grpc.CallOption) (*SendEmailCodeResponse, error)
	VerifyEmailCode(ctx context.Context, in *VerifyEmailCodeRequest, opts ...grpc.CallOption) (*VerifyEmailCodeResponse, error)
	LinkEmail(ctx context.Context, in *LinkEmailRequest, opts ...grpc.CallOption) (*LinkEmailResponse, error)
	ResetPassword(ctx context.Context, in *ResetPasswordRequest, opts ...grpc.CallOption) (*ResetPasswordResponse, error)
	CheckUsername(ctx context.Context, in *CheckUsernameRequest, opts ...grpc.CallOption) (*CheckUsernameResponse, error)
	DeleteAccount(ctx context.Context, in *DeleteAccountRequest, opts ...grpc.CallOption) (*DeleteAccountResponse, error)
	// Phase 2
	GoogleSignIn(ctx context.Context, in *GoogleSignInRequest, opts ...grpc.CallOption) (*GoogleSignInResponse, error)
	ClaimDailyReward(ctx context.Context, in *ClaimDailyRewardRequest, opts ...grpc.CallOption) (*ClaimDailyRewardResponse, error)
	GetStreakInfo(ctx context.Context, in *GetStreakInfoRequest, opts ...grpc.CallOption) (*GetStreakInfoResponse, error)
	// Phase 3
	UpdateProfile(ctx context.Context, in *UpdateProfileRequest, opts ...grpc.CallOption) (*UpdateProfileResponse, error)
}

type authServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAuthServiceClient(cc grpc.ClientConnInterface) AuthServiceClient {
	return &authServiceClient{cc}
}

func (c *authServiceClient) Register(ctx context.Context, in *RegisterRequest, opts ...grpc.CallOption) (*AuthResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AuthResponse)
	err := c.cc.Invoke(ctx, AuthService_Register_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authServiceClient) Login(ctx context.Context, in *LoginRequest, opts ...grpc.CallOption) (*AuthResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AuthResponse)
	err := c.cc.Invoke(ctx, AuthService_Login_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authServiceClient) GetProfile(ctx context.Context, in *GetProfileRequest, opts ...grpc.CallOption) (*ProfileResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ProfileResponse)
	err := c.cc.Invoke(ctx, AuthService_GetProfile_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authServiceClient) GuestLogin(ctx context.Context, in *GuestLoginRequest, opts ...grpc.CallOption) (*AuthResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AuthResponse)
	err := c.cc.Invoke(ctx, AuthService_GuestLogin_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authServiceClient) LoginWithEmail(ctx context.Context, in *EmailLoginRequest, opts ...grpc.CallOption) (*SendEmailCodeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SendEmailCodeResponse)
	err := c.cc.Invoke(ctx, AuthService_LoginWithEmail_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authServiceClient) SendEmailCode(ctx context.Context, in *SendEmailCodeRequest, opts ...grpc.CallOption) (*SendEmailCodeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SendEmailCodeResponse)
	err := c.cc.Invoke(ctx, AuthService_SendEmailCode_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authServiceClient) VerifyEmailCode(ctx context.Context, in *VerifyEmailCodeRequest, opts ...grpc.CallOption) (*VerifyEmailCodeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(VerifyEmailCodeResponse)
	err := c.cc.Invoke(ctx, AuthService_VerifyEmailCode_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authServiceClient) LinkEmail(ctx context.Context, in *LinkEmailRequest, opts ...grpc.CallOption) (*LinkEmailResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LinkEmailResponse)
	err := c.cc.Invoke(ctx, AuthService_LinkEmail_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authServiceClient) ResetPassword(ctx context.Context, in *ResetPasswordRequest, opts ...grpc.CallOption) (*ResetPasswordResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ResetPasswordResponse)
	err := c.cc.Invoke(ctx, AuthService_ResetPassword_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authServiceClient) CheckUsername(ctx context.Context, in *CheckUsernameRequest, opts ...grpc.CallOption) (*CheckUsernameResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CheckUsernameResponse)
	err := c.cc.Invoke(ctx, AuthService_CheckUsername_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authServiceClient) DeleteAccount(ctx context.Context, in *DeleteAccountRequest, opts ...grpc.CallOption) (*DeleteAccountResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteAccountResponse)
	err := c.cc.Invoke(ctx, AuthService_DeleteAccount_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authServiceClient) GoogleSignIn(ctx context.Context, in *GoogleSignInRequest, opts ...grpc.CallOption) (*GoogleSignInResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GoogleSignInResponse)
	err := c.cc.Invoke(ctx, AuthService_GoogleSignIn_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authServiceClient) ClaimDailyReward(ctx context.Context, in *ClaimDailyRewardRequest, opts ...grpc.CallOption) (*ClaimDailyRewardResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ClaimDailyRewardResponse)
	err := c.cc.Invoke(ctx, AuthService_ClaimDailyReward_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authServiceClient) GetStreakInfo(ctx context.Context, in *GetStreakInfoRequest, opts ...grpc.CallOption) (*GetStreakInfoResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetStreakInfoResponse)
	err := c.cc.Invoke(ctx, AuthService_GetStreakInfo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authServiceClient) UpdateProfile(ctx context.Context, in *UpdateProfileRequest, opts ...grpc.CallOption) (*UpdateProfileResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateProfileResponse)
	err := c.cc.Invoke(ctx, AuthService_UpdateProfile_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AuthServiceServer is the server API for AuthService service.
// All implementations must embed UnimplementedAuthServiceServer
// for forward compatibility.
type AuthServiceServer interface {
	Register(context.Context, *RegisterRequest) (*AuthResponse, error)
	Login(context.Context, *LoginRequest) (*AuthResponse, error)
	GetProfile(context.Context, *GetProfileRequest) (*ProfileResponse, error)
	GuestLogin(context.Context, *GuestLoginRequest) (*AuthResponse, error)
	LoginWithEmail(context.Context, *EmailLoginRequest) (*SendEmailCodeResponse, error)
	SendEmailCode(context.Context, *SendEmailCodeRequest) (*SendEmailCodeResponse, error)
	VerifyEmailCode(context.Context, *VerifyEmailCodeRequest) (*VerifyEmailCodeResponse, error)
	LinkEmail(context.Context, *LinkEmailRequest) (*LinkEmailResponse, error)
	ResetPassword(context.Context, *ResetPasswordRequest) (*ResetPasswordResponse, error)
	CheckUsername(context.Context, *CheckUsernameRequest) (*CheckUsernameResponse, error)
	DeleteAccount(context.Context, *DeleteAccountRequest) (*DeleteAccountResponse, error)
	// Phase 2
	GoogleSignIn(context.Context, *GoogleSignInRequest) (*GoogleSignInResponse, error)
	ClaimDailyReward(context.Context, *ClaimDailyRewardRequest) (*ClaimDailyRewardResponse, error)
	GetStreakInfo(context.Context, *GetStreakInfoRequest) (*GetStreakInfoResponse, error)
	// Phase 3
	UpdateProfile(context.Context, *UpdateProfileRequest) (*UpdateProfileResponse, error)
	mustEmbedUnimplementedAuthServiceServer()
}

// UnimplementedAuthServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAuthServiceServer struct{}

func (UnimplementedAuthServiceServer) Register(context.Context, *RegisterRequest) (*AuthResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Register not implemented")
}
func (UnimplementedAuthServiceServer) Login(context.Context, *LoginRequest) (*AuthResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Login not implemented")
}
func (UnimplementedAuthServiceServer) GetProfile(context.Context, *GetProfileRequest) (*ProfileResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetProfile not implemented")
}
func (UnimplementedAuthServiceServer) GuestLogin(context.Context, *GuestLoginRequest) (*AuthResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GuestLogin not implemented")
}
func (UnimplementedAuthServiceServer) LoginWithEmail(context.Context, *EmailLoginRequest) (*SendEmailCodeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method LoginWithEmail not implemented")
}
func (UnimplementedAuthServiceServer) SendEmailCode(context.Context, *SendEmailCodeRequest) (*SendEmailCodeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SendEmailCode not implemented")
}
func (UnimplementedAuthServiceServer) VerifyEmailCode(context.Context, *VerifyEmailCodeRequest) (*VerifyEmailCodeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method VerifyEmailCode not implemented")
}
func (UnimplementedAuthServiceServer) LinkEmail(context.Context, *LinkEmailRequest) (*LinkEmailResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method LinkEmail not implemented")
}
func (UnimplementedAuthServiceServer) ResetPassword(context.Context, *ResetPasswordRequest) (*ResetPasswordResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ResetPassword not implemented")
}
func (UnimplementedAuthServiceServer) CheckUsername(context.Context, *CheckUsernameRequest) (*CheckUsernameResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CheckUsername not implemented")
}
func (UnimplementedAuthServiceServer) DeleteAccount(context.Context, *DeleteAccountRequest) (*DeleteAccountResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteAccount not implemented")
}
func (UnimplementedAuthServiceServer) GoogleSignIn(context.Context, *GoogleSignInRequest) (*GoogleSignInResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GoogleSignIn not implemented")
}
func (UnimplementedAuthServiceServer) ClaimDailyReward(context.Context, *ClaimDailyRewardRequest) (*ClaimDailyRewardResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ClaimDailyReward not implemented")
}
func (UnimplementedAuthServiceServer) GetStreakInfo(context.Context, *GetStreakInfoRequest) (*GetStreakInfoResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetStreakInfo not implemented")
}
func (UnimplementedAuthServiceServer) UpdateProfile(context.Context, *UpdateProfileRequest) (*UpdateProfileResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateProfile not implemented")
}
func (UnimplementedAuthServiceServer) mustEmbedUnimplementedAuthServiceServer() {}
func (UnimplementedAuthServiceServer) testEmbeddedByValue()                     {}

// UnsafeAuthServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AuthServiceServer will
// result in compilation errors.
type UnsafeAuthServiceServer interface {
	mustEmbedUnimplementedAuthServiceServer()
}

func RegisterAuthServiceServer(s grpc.ServiceRegistrar, srv AuthServiceServer) {
	// If the following call panics, it indicates UnimplementedAuthServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AuthService_ServiceDesc, srv)
}

func _AuthService_Register_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServiceServer).Register(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AuthService_Register_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServiceServer).Register(ctx, req.(*RegisterRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthService_Login_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LoginRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServiceServer).Login(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AuthService_Login_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServiceServer).Login(ctx, req.(*LoginRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthService_GetProfile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetProfileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServiceServer).GetProfile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AuthService_GetProfile_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServiceServer).GetProfile(ctx, req.(*GetProfileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthService_GuestLogin_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GuestLoginRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServiceServer).GuestLogin(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AuthService_GuestLogin_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServiceServer).GuestLogin(ctx, req.(*GuestLoginRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthService_LoginWithEmail_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EmailLoginRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServiceServer).LoginWithEmail(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AuthService_LoginWithEmail_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServiceServer).LoginWithEmail(ctx, req.(*EmailLoginRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthService_SendEmailCode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SendEmailCodeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServiceServer).SendEmailCode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AuthService_SendEmailCode_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServiceServer).SendEmailCode(ctx, req.(*SendEmailCodeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthService_VerifyEmailCode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VerifyEmailCodeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServiceServer).VerifyEmailCode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AuthService_VerifyEmailCode_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServiceServer).VerifyEmailCode(ctx, req.(*VerifyEmailCodeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthService_LinkEmail_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LinkEmailRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServiceServer).LinkEmail(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AuthService_LinkEmail_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServiceServer).LinkEmail(ctx, req.(*LinkEmailRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthService_ResetPassword_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ResetPasswordRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServiceServer).ResetPassword(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AuthService_ResetPassword_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServiceServer).ResetPassword(ctx, req.(*ResetPasswordRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthService_CheckUsername_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CheckUsernameRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServiceServer).CheckUsername(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AuthService_CheckUsername_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServiceServer).CheckUsername(ctx, req.(*CheckUsernameRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthService_DeleteAccount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteAccountRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServiceServer).DeleteAccount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AuthService_DeleteAccount_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServiceServer).DeleteAccount(ctx, req.(*DeleteAccountRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthService_GoogleSignIn_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GoogleSignInRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServiceServer).GoogleSignIn(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AuthService_GoogleSignIn_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServiceServer).GoogleSignIn(ctx, req.(*GoogleSignInRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthService_ClaimDailyReward_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ClaimDailyRewardRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServiceServer).ClaimDailyReward(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AuthService_ClaimDailyReward_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServiceServer).ClaimDailyReward(ctx, req.(*ClaimDailyRewardRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthService_GetStreakInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetStreakInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServiceServer).GetStreakInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AuthService_GetStreakInfo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServiceServer).GetStreakInfo(ctx, req.(*GetStreakInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthService_UpdateProfile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateProfileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServiceServer).UpdateProfile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AuthService_UpdateProfile_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServiceServer).UpdateProfile(ctx, req.(*UpdateProfileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AuthService_ServiceDesc is the grpc.ServiceDesc for AuthService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AuthService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "quiz.AuthService",
	HandlerType: (*AuthServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Register",
			Handler:    _AuthService_Register_Handler,
		},
		{
			MethodName: "Login",
			Handler:    _AuthService_Login_Handler,
		},
		{
			MethodName: "GetProfile",
			Handler:    _AuthService_GetProfile_Handler,
		},
		{
			MethodName: "GuestLogin",
			Handler:    _AuthService_GuestLogin_Handler,
		},
		{
			MethodName: "LoginWithEmail",
			Handler:    _AuthService_LoginWithEmail_Handler,
		},
		{
			MethodName: "SendEmailCode",
			Handler:    _AuthService_SendEmailCode_Handler,
		},
		{
			MethodName: "VerifyEmailCode",
			Handler:    _AuthService_VerifyEmailCode_Handler,
		},
		{
			MethodName: "LinkEmail",
			Handler:    _AuthService_LinkEmail_Handler,
		},
		{
			MethodName: "ResetPassword",
			Handler:    _AuthService_ResetPassword_Handler,
		},
		{
			MethodName: "CheckUsername",
			Handler:    _AuthService_CheckUsername_Handler,
		},
		{
			MethodName: "DeleteAccount",
			Handler:    _AuthService_DeleteAccount_Handler,
		},
		{
			MethodName: "GoogleSignIn",
			Handler:    _AuthService_GoogleSignIn_Handler,
		},
		{
			MethodName: "ClaimDailyReward",
			Handler:    _AuthService_ClaimDailyReward_Handler,
		},
		{
			MethodName: "GetStreakInfo",
			Handler:    _AuthService_GetStreakInfo_Handler,
		},
		{
			MethodName: "UpdateProfile",
			Handler:    _AuthService_UpdateProfile_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "quiz.proto",
}

const (
	PaymentService_CreateOrder_FullMethodName       = "/quiz.PaymentService/CreateOrder"
	PaymentService_GetPlanStatus_FullMethodName     = "/quiz.PaymentService/GetPlanStatus"
	PaymentService_GetPaymentHistory_FullMethodName = "/quiz.PaymentService/GetPaymentHistory"
)

// PaymentServiceClient is the client API for PaymentService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PaymentServiceClient interface {
	CreateOrder(ctx context.Context, in *CreateOrderRequest, opts ...grpc.CallOption) (*CreateOrderResponse, error)
	GetPlanStatus(ctx context.Context, in *GetPlanStatusRequest, opts ...grpc.CallOption) (*GetPlanStatusResponse, error)
	GetPaymentHistory(ctx context.Context, in *GetPaymentHistoryRequest, opts ...grpc.CallOption) (*GetPaymentHistoryResponse, error)
}

type paymentServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewPaymentServiceClient(cc grpc.ClientConnInterface) PaymentServiceClient {
	return &paymentServiceClient{cc}
}

func (c *paymentServiceClient) CreateOrder(ctx context.Context, in *CreateOrderRequest, opts ...grpc.CallOption) (*CreateOrderResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateOrderResponse)
	err := c.cc.Invoke(ctx, PaymentService_CreateOrder_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *paymentServiceClient) GetPlanStatus(ctx context.Context, in *GetPlanStatusRequest, opts ...grpc.CallOption) (*GetPlanStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetPlanStatusResponse)
	err := c.cc.Invoke(ctx, PaymentService_GetPlanStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *paymentServiceClient) GetPaymentHistory(ctx context.Context, in *GetPaymentHistoryRequest, opts ...grpc.CallOption) (*GetPaymentHistoryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetPaymentHistoryResponse)
	err := c.cc.Invoke(ctx, PaymentService_GetPaymentHistory_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PaymentServiceServer is the server API for PaymentService service.
// All implementations must embed UnimplementedPaymentServiceServer
// for forward compatibility.
type PaymentServiceServer interface {
	CreateOrder(context.Context, *CreateOrderRequest) (*CreateOrderResponse, error)
	GetPlanStatus(context.Context, *GetPlanStatusRequest) (*GetPlanStatusResponse, error)
	GetPaymentHistory(context.Context, *GetPaymentHistoryRequest) (*GetPaymentHistoryResponse, error)
	mustEmbedUnimplementedPaymentServiceServer()
}

// UnimplementedPaymentServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedPaymentServiceServer struct{}

func (UnimplementedPaymentServiceServer) CreateOrder(context.Context, *CreateOrderRequest) (*CreateOrderResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateOrder not implemented")
}
func (UnimplementedPaymentServiceServer) GetPlanStatus(context.Context, *GetPlanStatusRequest) (*GetPlanStatusResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetPlanStatus not implemented")
}
func (UnimplementedPaymentServiceServer) GetPaymentHistory(context.Context, *GetPaymentHistoryRequest) (*GetPaymentHistoryResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetPaymentHistory not implemented")
}
func (UnimplementedPaymentServiceServer) mustEmbedUnimplementedPaymentServiceServer() {}
func (UnimplementedPaymentServiceServer) testEmbeddedByValue()                        {}

// UnsafePaymentServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PaymentServiceServer will
// result in compilation errors.
type UnsafePaymentServiceServer interface {
	mustEmbedUnimplementedPaymentServiceServer()
}

func RegisterPaymentServiceServer(s grpc.ServiceRegistrar, srv PaymentServiceServer) {
	// If the following call panics, it indicates UnimplementedPaymentServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&PaymentService_ServiceDesc, srv)
}

func _PaymentService_CreateOrder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateOrderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PaymentServiceServer).CreateOrder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PaymentService_CreateOrder_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PaymentServiceServer).CreateOrder(ctx, req.(*CreateOrderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PaymentService_GetPlanStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPlanStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PaymentServiceServer).GetPlanStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PaymentService_GetPlanStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PaymentServiceServer).GetPlanStatus(ctx, req.(*GetPlanStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PaymentService_GetPaymentHistory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPaymentHistoryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PaymentServiceServer).GetPaymentHistory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PaymentService_GetPaymentHistory_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PaymentServiceServer).GetPaymentHistory(ctx, req.(*GetPaymentHistoryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// PaymentService_ServiceDesc is the grpc.ServiceDesc for PaymentService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PaymentService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "quiz.PaymentService",
	HandlerType: (*PaymentServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateOrder",
			Handler:    _PaymentService_CreateOrder_Handler,
		},
		{
			MethodName: "GetPlanStatus",
			Handler:    _PaymentService_GetPlanStatus_Handler,
		},
		{
			MethodName: "GetPaymentHistory",
			Handler:    _PaymentService_GetPaymentHistory_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "quiz.proto",
}
