// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v4.25.1
// source: proto/quiz.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MatchmakingStatus int32

const (
	MatchmakingStatus_QUEUED           MatchmakingStatus = 0
	MatchmakingStatus_ALREADY_IN_QUEUE MatchmakingStatus = 1
)

// Enum value maps for MatchmakingStatus.
var (
	MatchmakingStatus_name = map[int32]string{
		0: "QUEUED",
		1: "ALREADY_IN_QUEUE",
	}
	MatchmakingStatus_value = map[string]int32{
		"QUEUED":           0,
		"ALREADY_IN_QUEUE": 1,
	}
)

func (x MatchmakingStatus) Enum() *MatchmakingStatus {
	p := new(MatchmakingStatus)
	*p = x
	return p
}

func (x MatchmakingStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MatchmakingStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_quiz_proto_enumTypes[0].Descriptor()
}

func (MatchmakingStatus) Type() protoreflect.EnumType {
	return &file_proto_quiz_proto_enumTypes[0]
}

func (x MatchmakingStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MatchmakingStatus.Descriptor instead.
func (MatchmakingStatus) EnumDescriptor() ([]byte, []int) {
	return file_proto_quiz_proto_rawDescGZIP(), []int{0}
}

type JoinMatchmakingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Rating        int32                  `protobuf:"varint,2,opt,name=rating,proto3" json:"rating,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JoinMatchmakingRequest) Reset() {
	*x = JoinMatchmakingRequest{}
	mi := &file_proto_quiz_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JoinMatchmakingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoinMatchmakingRequest) ProtoMessage() {}

func (x *JoinMatchmakingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_quiz_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoinMatchmakingRequest.ProtoReflect.Descriptor instead.
func (*JoinMatchmakingRequest) Descriptor() ([]byte, []int) {
	return file_proto_quiz_proto_rawDescGZIP(), []int{0}
}

func (x *JoinMatchmakingRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *JoinMatchmakingRequest) GetRating() int32 {
	if x != nil {
		return x.Rating
	}
	return 0
}

type JoinMatchmakingResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        MatchmakingStatus      `protobuf:"varint,1,opt,name=status,proto3,enum=quiz.MatchmakingStatus" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JoinMatchmakingResponse) Reset() {
	*x = JoinMatchmakingResponse{}
	mi := &file_proto_quiz_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JoinMatchmakingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoinMatchmakingResponse) ProtoMessage() {}

func (x *JoinMatchmakingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_quiz_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoinMatchmakingResponse.ProtoReflect.Descriptor instead.
func (*JoinMatchmakingResponse) Descriptor() ([]byte, []int) {
	return file_proto_quiz_proto_rawDescGZIP(), []int{1}
}

func (x *JoinMatchmakingResponse) GetStatus() MatchmakingStatus {
	if x != nil {
		return x.Status
	}
	return MatchmakingStatus_QUEUED
}

type LeaveMatchmakingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LeaveMatchmakingRequest) Reset() {
	*x = LeaveMatchmakingRequest{}
	mi := &file_proto_quiz_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LeaveMatchmakingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LeaveMatchmakingRequest) ProtoMessage() {}

func (x *LeaveMatchmakingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_quiz_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LeaveMatchmakingRequest.ProtoReflect.Descriptor instead.
func (*LeaveMatchmakingRequest) Descriptor() ([]byte, []int) {
	return file_proto_quiz_proto_rawDescGZIP(), []int{2}
}

func (x *LeaveMatchmakingRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type LeaveMatchmakingResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Removed       bool                   `protobuf:"varint,1,opt,name=removed,proto3" json:"removed,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LeaveMatchmakingResponse) Reset() {
	*x = LeaveMatchmakingResponse{}
	mi := &file_proto_quiz_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LeaveMatchmakingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LeaveMatchmakingResponse) ProtoMessage() {}

func (x *LeaveMatchmakingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_quiz_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LeaveMatchmakingResponse.ProtoReflect.Descriptor instead.
func (*LeaveMatchmakingResponse) Descriptor() ([]byte, []int) {
	return file_proto_quiz_proto_rawDescGZIP(), []int{3}
}

func (x *LeaveMatchmakingResponse) GetRemoved() bool {
	if x != nil {
		return x.Removed
	}
	return false
}

type SubscribeToMatchRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	UserId         string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	SequenceNumber int64                  `protobuf:"varint,2,opt,name=sequence_number,json=sequenceNumber,proto3" json:"sequence_number,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *SubscribeToMatchRequest) Reset() {
	*x = SubscribeToMatchRequest{}
	mi := &file_proto_quiz_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubscribeToMatchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscribeToMatchRequest) ProtoMessage() {}

func (x *SubscribeToMatchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_quiz_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscribeToMatchRequest.ProtoReflect.Descriptor instead.
func (*SubscribeToMatchRequest) Descriptor() ([]byte, []int) {
	return file_proto_quiz_proto_rawDescGZIP(), []int{4}
}

func (x *SubscribeToMatchRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *SubscribeToMatchRequest) GetSequenceNumber() int64 {
	if x != nil {
		return x.SequenceNumber
	}
	return 0
}

type MatchEvent struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	RoomId         string                 `protobuf:"bytes,1,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	Players        []string               `protobuf:"bytes,2,rep,name=players,proto3" json:"players,omitempty"`
	SequenceNumber int64                  `protobuf:"varint,3,opt,name=sequence_number,json=sequenceNumber,proto3" json:"sequence_number,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *MatchEvent) Reset() {
	*x = MatchEvent{}
	mi := &file_proto_quiz_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MatchEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MatchEvent) ProtoMessage() {}

func (x *MatchEvent) ProtoReflect() protoreflect.Message {
	mi := &file_proto_quiz_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MatchEvent.ProtoReflect.Descriptor instead.
func (*MatchEvent) Descriptor() ([]byte, []int) {
	return file_proto_quiz_proto_rawDescGZIP(), []int{5}
}

func (x *MatchEvent) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

func (x *MatchEvent) GetPlayers() []string {
	if x != nil {
		return x.Players
	}
	return nil
}

func (x *MatchEvent) GetSequenceNumber() int64 {
	if x != nil {
		return x.SequenceNumber
	}
	return 0
}

type GetRoomQuestionsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoomId        string                 `protobuf:"bytes,1,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRoomQuestionsRequest) Reset() {
	*x = GetRoomQuestionsRequest{}
	mi := &file_proto_quiz_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRoomQuestionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRoomQuestionsRequest) ProtoMessage() {}

func (x *GetRoomQuestionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_quiz_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRoomQuestionsRequest.ProtoReflect.Descriptor instead.
func (*GetRoomQuestionsRequest) Descriptor() ([]byte, []int) {
	return file_proto_quiz_proto_rawDescGZIP(), []int{6}
}

func (x *GetRoomQuestionsRequest) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

type GetRoomQuestionsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Questions     []*Question            `protobuf:"bytes,1,rep,name=questions,proto3" json:"questions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRoomQuestionsResponse) Reset() {
	*x = GetRoomQuestionsResponse{}
	mi := &file_proto_quiz_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRoomQuestionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRoomQuestionsResponse) ProtoMessage() {}

func (x *GetRoomQuestionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_quiz_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRoomQuestionsResponse.ProtoReflect.Descriptor instead.
func (*GetRoomQuestionsResponse) Descriptor() ([]byte, []int) {
	return file_proto_quiz_proto_rawDescGZIP(), []int{7}
}

func (x *GetRoomQuestionsResponse) GetQuestions() []*Question {
	if x != nil {
		return x.Questions
	}
	return nil
}

type Question struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Text          string                 `protobuf:"bytes,2,opt,name=text,proto3" json:"text,omitempty"`
	Options       []string               `protobuf:"bytes,3,rep,name=options,proto3" json:"options,omitempty"`
	Difficulty    string                 `protobuf:"bytes,4,opt,name=difficulty,proto3" json:"difficulty,omitempty"`
	Topic         string                 `protobuf:"bytes,5,opt,name=topic,proto3" json:"topic,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Question) Reset() {
	*x = Question{}
	mi := &file_proto_quiz_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Question) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Question) ProtoMessage() {}

func (x *Question) ProtoReflect() protoreflect.Message {
	mi := &file_proto_quiz_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Question.ProtoReflect.Descriptor instead.
func (*Question) Descriptor() ([]byte, []int) {
	return file_proto_quiz_proto_rawDescGZIP(), []int{8}
}

func (x *Question) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Question) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *Question) GetOptions() []string {
	if x != nil {
		return x.Options
	}
	return nil
}

func (x *Question) GetDifficulty() string {
	if x != nil {
		return x.Difficulty
	}
	return ""
}

func (x *Question) GetTopic() string {
	if x != nil {
		return x.Topic
	}
	return ""
}

type SubmitAnswerRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	RoomId          string                 `protobuf:"bytes,1,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	UserId          string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Round           int32                  `protobuf:"varint,3,opt,name=round,proto3" json:"round,omitempty"`
	OptionIndex     int32                  `protobuf:"varint,4,opt,name=option_index,json=optionIndex,proto3" json:"option_index,omitempty"`
	ClientTimestamp int64                  `protobuf:"varint,5,opt,name=client_timestamp,json=clientTimestamp,proto3" json:"client_timestamp,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *SubmitAnswerRequest) Reset() {
	*x = SubmitAnswerRequest{}
	mi := &file_proto_quiz_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubmitAnswerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitAnswerRequest) ProtoMessage() {}

func (x *SubmitAnswerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_quiz_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitAnswerRequest.ProtoReflect.Descriptor instead.
func (*SubmitAnswerRequest) Descriptor() ([]byte, []int) {
	return file_proto_quiz_proto_rawDescGZIP(), []int{9}
}

func (x *SubmitAnswerRequest) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

func (x *SubmitAnswerRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *SubmitAnswerRequest) GetRound() int32 {
	if x != nil {
		return x.Round
	}
	return 0
}

func (x *SubmitAnswerRequest) GetOptionIndex() int32 {
	if x != nil {
		return x.OptionIndex
	}
	return 0
}

func (x *SubmitAnswerRequest) GetClientTimestamp() int64 {
	if x != nil {
		return x.ClientTimestamp
	}
	return 0
}

type SubmitAnswerResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Accepted      bool                   `protobuf:"varint,1,opt,name=accepted,proto3" json:"accepted,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubmitAnswerResponse) Reset() {
	*x = SubmitAnswerResponse{}
	mi := &file_proto_quiz_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubmitAnswerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitAnswerResponse) ProtoMessage() {}

func (x *SubmitAnswerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_quiz_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitAnswerResponse.ProtoReflect.Descriptor instead.
func (*SubmitAnswerResponse) Descriptor() ([]byte, []int) {
	return file_proto_quiz_proto_rawDescGZIP(), []int{10}
}

func (x *SubmitAnswerResponse) GetAccepted() bool {
	if x != nil {
		return x.Accepted
	}
	return false
}

type StreamGameEventsRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	RoomId         string                 `protobuf:"bytes,1,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	UserId         string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	SequenceNumber int64                  `protobuf:"varint,3,opt,name=sequence_number,json=sequenceNumber,proto3" json:"sequence_number,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *StreamGameEventsRequest) Reset() {
	*x = StreamGameEventsRequest{}
	mi := &file_proto_quiz_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamGameEventsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamGameEventsRequest) ProtoMessage() {}

func (x *StreamGameEventsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_quiz_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamGameEventsRequest.ProtoReflect.Descriptor instead.
func (*StreamGameEventsRequest) Descriptor() ([]byte, []int) {
	return file_proto_quiz_proto_rawDescGZIP(), []int{11}
}

func (x *StreamGameEventsRequest) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

func (x *StreamGameEventsRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *StreamGameEventsRequest) GetSequenceNumber() int64 {
	if x != nil {
		return x.SequenceNumber
	}
	return 0
}

type GameEvent struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	SequenceNumber int64                  `protobuf:"varint,7,opt,name=sequence_number,json=sequenceNumber,proto3" json:"sequence_number,omitempty"`
	// Types that are valid to be assigned to Event:
	//
	//	*GameEvent_Question
	//	*GameEvent_Leaderboard
	//	*GameEvent_RoundResult
	//	*GameEvent_MatchEnd
	//	*GameEvent_PlayerJoined
	//	*GameEvent_TimerSync
	Event         isGameEvent_Event `protobuf_oneof:"event"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GameEvent) Reset() {
	*x = GameEvent{}
	mi := &file_proto_quiz_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GameEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GameEvent) ProtoMessage() {}

func (x *GameEvent) ProtoReflect() protoreflect.Message {
	mi := &file_proto_quiz_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GameEvent.ProtoReflect.Descriptor instead.
func (*GameEvent) Descriptor() ([]byte, []int) {
	return file_proto_quiz_proto_rawDescGZIP(), []int{12}
}

func (x *GameEvent) GetSequenceNumber() int64 {
	if x != nil {
		return x.SequenceNumber
	}
	return 0
}

func (x *GameEvent) GetEvent() isGameEvent_Event {
	if x != nil {
		return x.Event
	}
	return nil
}

func (x *GameEvent) GetQuestion() *QuestionBroadcast {
	if x != nil {
		if x, ok := x.Event.(*GameEvent_Question); ok {
			return x.Question
		}
	}
	return nil
}

func (x *GameEvent) GetLeaderboard() *LeaderboardUpdate {
	if x != nil {
		if x, ok := x.Event.(*GameEvent_Leaderboard); ok {
			return x.Leaderboard
		}
	}
	return nil
}

func (x *GameEvent) GetRoundResult() *RoundResult {
	if x != nil {
		if x, ok := x.Event.(*GameEvent_RoundResult); ok {
			return x.RoundResult
		}
	}
	return nil
}

func (x *GameEvent) GetMatchEnd() *MatchEnd {
	if x != nil {
		if x, ok := x.Event.(*GameEvent_MatchEnd); ok {
			return x.MatchEnd
		}
	}
	return nil
}

func (x *GameEvent) GetPlayerJoined() *PlayerJoined {
	if x != nil {
		if x, ok := x.Event.(*GameEvent_PlayerJoined); ok {
			return x.PlayerJoined
		}
	}
	return nil
}

func (x *GameEvent) GetTimerSync() *TimerSync {
	if x != nil {
		if x, ok := x.Event.(*GameEvent_TimerSync); ok {
			return x.TimerSync
		}
	}
	return nil
}

type isGameEvent_Event interface {
	isGameEvent_Event()
}

type GameEvent_Question struct {
	Question *QuestionBroadcast `protobuf:"bytes,1,opt,name=question,proto3,oneof"`
}

type GameEvent_Leaderboard struct {
	Leaderboard *LeaderboardUpdate `protobuf:"bytes,2,opt,name=leaderboard,proto3,oneof"`
}

type GameEvent_RoundResult struct {
	RoundResult *RoundResult `protobuf:"bytes,3,opt,name=round_result,json=roundResult,proto3,oneof"`
}

type GameEvent_MatchEnd struct {
	MatchEnd *MatchEnd `protobuf:"bytes,4,opt,name=match_end,json=matchEnd,proto3,oneof"`
}

type GameEvent_PlayerJoined struct {
	PlayerJoined *PlayerJoined `protobuf:"bytes,5,opt,name=player_joined,json=playerJoined,proto3,oneof"`
}

type GameEvent_TimerSync struct {
	TimerSync *TimerSync `protobuf:"bytes,6,opt,name=timer_sync,json=timerSync,proto3,oneof"`
}

func (*GameEvent_Question) isGameEvent_Event() {}

func (*GameEvent_Leaderboard) isGameEvent_Event() {}

func (*GameEvent_RoundResult) isGameEvent_Event() {}

func (*GameEvent_MatchEnd) isGameEvent_Event() {}

func (*GameEvent_PlayerJoined) isGameEvent_Event() {}

func (*GameEvent_TimerSync) isGameEvent_Event() {}

type QuestionBroadcast struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	QuestionId    string                 `protobuf:"bytes,1,opt,name=question_id,json=questionId,proto3" json:"question_id,omitempty"`
	Text          string                 `protobuf:"bytes,2,opt,name=text,proto3" json:"text,omitempty"`
	Options       []string               `protobuf:"bytes,3,rep,name=options,proto3" json:"options,omitempty"`
	DeadlineUnix  int64                  `protobuf:"varint,4,opt,name=deadline_unix,json=deadlineUnix,proto3" json:"deadline_unix,omitempty"`
	Round         int32                  `protobuf:"varint,5,opt,name=round,proto3" json:"round,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QuestionBroadcast) Reset() {
	*x = QuestionBroadcast{}
	mi := &file_proto_quiz_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QuestionBroadcast) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QuestionBroadcast) ProtoMessage() {}

func (x *QuestionBroadcast) ProtoReflect() protoreflect.Message {
	mi := &file_proto_quiz_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QuestionBroadcast.ProtoReflect.Descriptor instead.
func (*QuestionBroadcast) Descriptor() ([]byte, []int) {
	return file_proto_quiz_proto_rawDescGZIP(), []int{13}
}

func (x *QuestionBroadcast) GetQuestionId() string {
	if x != nil {
		return x.QuestionId
	}
	return ""
}

func (x *QuestionBroadcast) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *QuestionBroadcast) GetOptions() []string {
	if x != nil {
		return x.Options
	}
	return nil
}

func (x *QuestionBroadcast) GetDeadlineUnix() int64 {
	if x != nil {
		return x.DeadlineUnix
	}
	return 0
}

func (x *QuestionBroadcast) GetRound() int32 {
	if x != nil {
		return x.Round
	}
	return 0
}

type LeaderboardUpdate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Entries       []*LeaderboardEntry    `protobuf:"bytes,1,rep,name=entries,proto3" json:"entries,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LeaderboardUpdate) Reset() {
	*x = LeaderboardUpdate{}
	mi := &file_proto_quiz_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LeaderboardUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LeaderboardUpdate) ProtoMessage() {}

func (x *LeaderboardUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_proto_quiz_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LeaderboardUpdate.ProtoReflect.Descriptor instead.
func (*LeaderboardUpdate) Descriptor() ([]byte, []int) {
	return file_proto_quiz_proto_rawDescGZIP(), []int{14}
}

func (x *LeaderboardUpdate) GetEntries() []*LeaderboardEntry {
	if x != nil {
		return x.Entries
	}
	return nil
}

type LeaderboardEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Username      string                 `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	Score         float64                `protobuf:"fixed64,3,opt,name=score,proto3" json:"score,omitempty"`
	Rank          int32                  `protobuf:"varint,4,opt,name=rank,proto3" json:"rank,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LeaderboardEntry) Reset() {
	*x = LeaderboardEntry{}
	mi := &file_proto_quiz_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LeaderboardEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LeaderboardEntry) ProtoMessage() {}

func (x *LeaderboardEntry) ProtoReflect() protoreflect.Message {
	mi := &file_proto_quiz_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LeaderboardEntry.ProtoReflect.Descriptor instead.
func (*LeaderboardEntry) Descriptor() ([]byte, []int) {
	return file_proto_quiz_proto_rawDescGZIP(), []int{15}
}

func (x *LeaderboardEntry) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *LeaderboardEntry) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *LeaderboardEntry) GetScore() float64 {
	if x != nil {
		return x.Score
	}
	return 0
}

func (x *LeaderboardEntry) GetRank() int32 {
	if x != nil {
		return x.Rank
	}
	return 0
}

type RoundResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Round         int32                  `protobuf:"varint,1,opt,name=round,proto3" json:"round,omitempty"`
	CorrectIndex  int32                  `protobuf:"varint,2,opt,name=correct_index,json=correctIndex,proto3" json:"correct_index,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RoundResult) Reset() {
	*x = RoundResult{}
	mi := &file_proto_quiz_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RoundResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoundResult) ProtoMessage() {}

func (x *RoundResult) ProtoReflect() protoreflect.Message {
	mi := &file_proto_quiz_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoundResult.ProtoReflect.Descriptor instead.
func (*RoundResult) Descriptor() ([]byte, []int) {
	return file_proto_quiz_proto_rawDescGZIP(), []int{16}
}

func (x *RoundResult) GetRound() int32 {
	if x != nil {
		return x.Round
	}
	return 0
}

func (x *RoundResult) GetCorrectIndex() int32 {
	if x != nil {
		return x.CorrectIndex
	}
	return 0
}

type MatchEnd struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoomId        string                 `protobuf:"bytes,1,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	Winner        string                 `protobuf:"bytes,2,opt,name=winner,proto3" json:"winner,omitempty"`
	Players       []*PlayerResult        `protobuf:"bytes,3,rep,name=players,proto3" json:"players,omitempty"`
	Rounds        int32                  `protobuf:"varint,4,opt,name=rounds,proto3" json:"rounds,omitempty"`
	Duration      int64                  `protobuf:"varint,5,opt,name=duration,proto3" json:"duration,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MatchEnd) Reset() {
	*x = MatchEnd{}
	mi := &file_proto_quiz_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MatchEnd) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MatchEnd) ProtoMessage() {}

func (x *MatchEnd) ProtoReflect() protoreflect.Message {
	mi := &file_proto_quiz_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MatchEnd.ProtoReflect.Descriptor instead.
func (*MatchEnd) Descriptor() ([]byte, []int) {
	return file_proto_quiz_proto_rawDescGZIP(), []int{17}
}

func (x *MatchEnd) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

func (x *MatchEnd) GetWinner() string {
	if x != nil {
		return x.Winner
	}
	return ""
}

func (x *MatchEnd) GetPlayers() []*PlayerResult {
	if x != nil {
		return x.Players
	}
	return nil
}

func (x *MatchEnd) GetRounds() int32 {
	if x != nil {
		return x.Rounds
	}
	return 0
}

func (x *MatchEnd) GetDuration() int64 {
	if x != nil {
		return x.Duration
	}
	return 0
}

type PlayerResult struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	UserId            string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Username          string                 `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	FinalScore        float64                `protobuf:"fixed64,3,opt,name=final_score,json=finalScore,proto3" json:"final_score,omitempty"`
	Rank              int32                  `protobuf:"varint,4,opt,name=rank,proto3" json:"rank,omitempty"`
	AnswersCorrect    int32                  `protobuf:"varint,5,opt,name=answers_correct,json=answersCorrect,proto3" json:"answers_correct,omitempty"`
	AvgResponseTimeMs float64                `protobuf:"fixed64,6,opt,name=avg_response_time_ms,json=avgResponseTimeMs,proto3" json:"avg_response_time_ms,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *PlayerResult) Reset() {
	*x = PlayerResult{}
	mi := &file_proto_quiz_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlayerResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerResult) ProtoMessage() {}

func (x *PlayerResult) ProtoReflect() protoreflect.Message {
	mi := &file_proto_quiz_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerResult.ProtoReflect.Descriptor instead.
func (*PlayerResult) Descriptor() ([]byte, []int) {
	return file_proto_quiz_proto_rawDescGZIP(), []int{18}
}

func (x *PlayerResult) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *PlayerResult) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *PlayerResult) GetFinalScore() float64 {
	if x != nil {
		return x.FinalScore
	}
	return 0
}

func (x *PlayerResult) GetRank() int32 {
	if x != nil {
		return x.Rank
	}
	return 0
}

func (x *PlayerResult) GetAnswersCorrect() int32 {
	if x != nil {
		return x.AnswersCorrect
	}
	return 0
}

func (x *PlayerResult) GetAvgResponseTimeMs() float64 {
	if x != nil {
		return x.AvgResponseTimeMs
	}
	return 0
}

type PlayerJoined struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Username      string                 `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlayerJoined) Reset() {
	*x = PlayerJoined{}
	mi := &file_proto_quiz_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlayerJoined) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerJoined) ProtoMessage() {}

func (x *PlayerJoined) ProtoReflect() protoreflect.Message {
	mi := &file_proto_quiz_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerJoined.ProtoReflect.Descriptor instead.
func (*PlayerJoined) Descriptor() ([]byte, []int) {
	return file_proto_quiz_proto_rawDescGZIP(), []int{19}
}

func (x *PlayerJoined) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *PlayerJoined) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

type TimerSync struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DeadlineUnix  int64                  `protobuf:"varint,1,opt,name=deadline_unix,json=deadlineUnix,proto3" json:"deadline_unix,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TimerSync) Reset() {
	*x = TimerSync{}
	mi := &file_proto_quiz_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TimerSync) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TimerSync) ProtoMessage() {}

func (x *TimerSync) ProtoReflect() protoreflect.Message {
	mi := &file_proto_quiz_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TimerSync.ProtoReflect.Descriptor instead.
func (*TimerSync) Descriptor() ([]byte, []int) {
	return file_proto_quiz_proto_rawDescGZIP(), []int{20}
}

func (x *TimerSync) GetDeadlineUnix() int64 {
	if x != nil {
		return x.DeadlineUnix
	}
	return 0
}

type CalculateScoreRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoomId        string                 `protobuf:"bytes,1,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Round         int32                  `protobuf:"varint,3,opt,name=round,proto3" json:"round,omitempty"`
	OptionIndex   int32                  `protobuf:"varint,4,opt,name=option_index,json=optionIndex,proto3" json:"option_index,omitempty"`
	AnswerTimeMs  int64                  `protobuf:"varint,5,opt,name=answer_time_ms,json=answerTimeMs,proto3" json:"answer_time_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CalculateScoreRequest) Reset() {
	*x = CalculateScoreRequest{}
	mi := &file_proto_quiz_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CalculateScoreRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CalculateScoreRequest) ProtoMessage() {}

func (x *CalculateScoreRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_quiz_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CalculateScoreRequest.ProtoReflect.Descriptor instead.
func (*CalculateScoreRequest) Descriptor() ([]byte, []int) {
	return file_proto_quiz_proto_rawDescGZIP(), []int{21}
}

func (x *CalculateScoreRequest) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

func (x *CalculateScoreRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *CalculateScoreRequest) GetRound() int32 {
	if x != nil {
		return x.Round
	}
	return 0
}

func (x *CalculateScoreRequest) GetOptionIndex() int32 {
	if x != nil {
		return x.OptionIndex
	}
	return 0
}

func (x *CalculateScoreRequest) GetAnswerTimeMs() int64 {
	if x != nil {
		return x.AnswerTimeMs
	}
	return 0
}

type CalculateScoreResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Score           float64                `protobuf:"fixed64,1,opt,name=score,proto3" json:"score,omitempty"`
	Correct         bool                   `protobuf:"varint,2,opt,name=correct,proto3" json:"correct,omitempty"`
	SpeedMultiplier float64                `protobuf:"fixed64,3,opt,name=speed_multiplier,json=speedMultiplier,proto3" json:"speed_multiplier,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *CalculateScoreResponse) Reset() {
	*x = CalculateScoreResponse{}
	mi := &file_proto_quiz_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CalculateScoreResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CalculateScoreResponse) ProtoMessage() {}

func (x *CalculateScoreResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_quiz_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CalculateScoreResponse.ProtoReflect.Descriptor instead.
func (*CalculateScoreResponse) Descriptor() ([]byte, []int) {
	return file_proto_quiz_proto_rawDescGZIP(), []int{22}
}

func (x *CalculateScoreResponse) GetScore() float64 {
	if x != nil {
		return x.Score
	}
	return 0
}

func (x *CalculateScoreResponse) GetCorrect() bool {
	if x != nil {
		return x.Correct
	}
	return false
}

func (x *CalculateScoreResponse) GetSpeedMultiplier() float64 {
	if x != nil {
		return x.SpeedMultiplier
	}
	return 0
}

type GetLeaderboardRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoomId        string                 `protobuf:"bytes,1,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetLeaderboardRequest) Reset() {
	*x = GetLeaderboardRequest{}
	mi := &file_proto_quiz_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLeaderboardRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLeaderboardRequest) ProtoMessage() {}

func (x *GetLeaderboardRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_quiz_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLeaderboardRequest.ProtoReflect.Descriptor instead.
func (*GetLeaderboardRequest) Descriptor() ([]byte, []int) {
	return file_proto_quiz_proto_rawDescGZIP(), []int{23}
}

func (x *GetLeaderboardRequest) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

type GetLeaderboardResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Entries       []*LeaderboardEntry    `protobuf:"bytes,1,rep,name=entries,proto3" json:"entries,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetLeaderboardResponse) Reset() {
	*x = GetLeaderboardResponse{}
	mi := &file_proto_quiz_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLeaderboardResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLeaderboardResponse) ProtoMessage() {}

func (x *GetLeaderboardResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_quiz_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLeaderboardResponse.ProtoReflect.Descriptor instead.
func (*GetLeaderboardResponse) Descriptor() ([]byte, []int) {
	return file_proto_quiz_proto_rawDescGZIP(), []int{24}
}

func (x *GetLeaderboardResponse) GetEntries() []*LeaderboardEntry {
	if x != nil {
		return x.Entries
	}
	return nil
}

var File_proto_quiz_proto protoreflect.FileDescriptor

const file_proto_quiz_proto_rawDesc = "" +
	"\n" +
	"\x10proto/quiz.proto\x12\x04quiz\"I\n" +
	"\x16JoinMatchmakingRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x16\n" +
	"\x06rating\x18\x02 \x01(\x05R\x06rating\"J\n" +
	"\x17JoinMatchmakingResponse\x12/\n" +
	"\x06status\x18\x01 \x01(\x0e2\x17.quiz.MatchmakingStatusR\x06status\"2\n" +
	"\x17LeaveMatchmakingRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"4\n" +
	"\x18LeaveMatchmakingResponse\x12\x18\n" +
	"\aremoved\x18\x01 \x01(\bR\aremoved\"[\n" +
	"\x17SubscribeToMatchRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12'\n" +
	"\x0fsequence_number\x18\x02 \x01(\x03R\x0esequenceNumber\"h\n" +
	"\n" +
	"MatchEvent\x12\x17\n" +
	"\aroom_id\x18\x01 \x01(\tR\x06roomId\x12\x18\n" +
	"\aplayers\x18\x02 \x03(\tR\aplayers\x12'\n" +
	"\x0fsequence_number\x18\x03 \x01(\x03R\x0esequenceNumber\"2\n" +
	"\x17GetRoomQuestionsRequest\x12\x17\n" +
	"\aroom_id\x18\x01 \x01(\tR\x06roomId\"H\n" +
	"\x18GetRoomQuestionsResponse\x12,\n" +
	"\tquestions\x18\x01 \x03(\v2\x0e.quiz.QuestionR\tquestions\"~\n" +
	"\bQuestion\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04text\x18\x02 \x01(\tR\x04text\x12\x18\n" +
	"\aoptions\x18\x03 \x03(\tR\aoptions\x12\x1e\n" +
	"\n" +
	"difficulty\x18\x04 \x01(\tR\n" +
	"difficulty\x12\x14\n" +
	"\x05topic\x18\x05 \x01(\tR\x05topic\"\xab\x01\n" +
	"\x13SubmitAnswerRequest\x12\x17\n" +
	"\aroom_id\x18\x01 \x01(\tR\x06roomId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x14\n" +
	"\x05round\x18\x03 \x01(\x05R\x05round\x12!\n" +
	"\foption_index\x18\x04 \x01(\x05R\voptionIndex\x12)\n" +
	"\x10client_timestamp\x18\x05 \x01(\x03R\x0fclientTimestamp\"2\n" +
	"\x14SubmitAnswerResponse\x12\x1a\n" +
	"\baccepted\x18\x01 \x01(\bR\baccepted\"t\n" +
	"\x17StreamGameEventsRequest\x12\x17\n" +
	"\aroom_id\x18\x01 \x01(\tR\x06roomId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12'\n" +
	"\x0fsequence_number\x18\x03 \x01(\x03R\x0esequenceNumber\"\x85\x03\n" +
	"\tGameEvent\x12'\n" +
	"\x0fsequence_number\x18\a \x01(\x03R\x0esequenceNumber\x125\n" +
	"\bquestion\x18\x01 \x01(\v2\x17.quiz.QuestionBroadcastH\x00R\bquestion\x12;\n" +
	"\vleaderboard\x18\x02 \x01(\v2\x17.quiz.LeaderboardUpdateH\x00R\vleaderboard\x126\n" +
	"\fround_result\x18\x03 \x01(\v2\x11.quiz.RoundResultH\x00R\vroundResult\x12-\n" +
	"\tmatch_end\x18\x04 \x01(\v2\x0e.quiz.MatchEndH\x00R\bmatchEnd\x129\n" +
	"\rplayer_joined\x18\x05 \x01(\v2\x12.quiz.PlayerJoinedH\x00R\fplayerJoined\x120\n" +
	"\n" +
	"timer_sync\x18\x06 \x01(\v2\x0f.quiz.TimerSyncH\x00R\ttimerSyncB\a\n" +
	"\x05event\"\x9d\x01\n" +
	"\x11QuestionBroadcast\x12\x1f\n" +
	"\vquestion_id\x18\x01 \x01(\tR\n" +
	"questionId\x12\x12\n" +
	"\x04text\x18\x02 \x01(\tR\x04text\x12\x18\n" +
	"\aoptions\x18\x03 \x03(\tR\aoptions\x12#\n" +
	"\rdeadline_unix\x18\x04 \x01(\x03R\fdeadlineUnix\x12\x14\n" +
	"\x05round\x18\x05 \x01(\x05R\x05round\"E\n" +
	"\x11LeaderboardUpdate\x120\n" +
	"\aentries\x18\x01 \x03(\v2\x16.quiz.LeaderboardEntryR\aentries\"q\n" +
	"\x10LeaderboardEntry\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1a\n" +
	"\busername\x18\x02 \x01(\tR\busername\x12\x14\n" +
	"\x05score\x18\x03 \x01(\x01R\x05score\x12\x12\n" +
	"\x04rank\x18\x04 \x01(\x05R\x04rank\"H\n" +
	"\vRoundResult\x12\x14\n" +
	"\x05round\x18\x01 \x01(\x05R\x05round\x12#\n" +
	"\rcorrect_index\x18\x02 \x01(\x05R\fcorrectIndex\"\x9d\x01\n" +
	"\bMatchEnd\x12\x17\n" +
	"\aroom_id\x18\x01 \x01(\tR\x06roomId\x12\x16\n" +
	"\x06winner\x18\x02 \x01(\tR\x06winner\x12,\n" +
	"\aplayers\x18\x03 \x03(\v2\x12.quiz.PlayerResultR\aplayers\x12\x16\n" +
	"\x06rounds\x18\x04 \x01(\x05R\x06rounds\x12\x1a\n" +
	"\bduration\x18\x05 \x01(\x03R\bduration\"\xd2\x01\n" +
	"\fPlayerResult\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1a\n" +
	"\busername\x18\x02 \x01(\tR\busername\x12\x1f\n" +
	"\vfinal_score\x18\x03 \x01(\x01R\n" +
	"finalScore\x12\x12\n" +
	"\x04rank\x18\x04 \x01(\x05R\x04rank\x12'\n" +
	"\x0fanswers_correct\x18\x05 \x01(\x05R\x0eanswersCorrect\x12/\n" +
	"\x14avg_response_time_ms\x18\x06 \x01(\x01R\x11avgResponseTimeMs\"C\n" +
	"\fPlayerJoined\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1a\n" +
	"\busername\x18\x02 \x01(\tR\busername\"0\n" +
	"\tTimerSync\x12#\n" +
	"\rdeadline_unix\x18\x01 \x01(\x03R\fdeadlineUnix\"\xa8\x01\n" +
	"\x15CalculateScoreRequest\x12\x17\n" +
	"\aroom_id\x18\x01 \x01(\tR\x06roomId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x14\n" +
	"\x05round\x18\x03 \x01(\x05R\x05round\x12!\n" +
	"\foption_index\x18\x04 \x01(\x05R\voptionIndex\x12$\n" +
	"\x0eanswer_time_ms\x18\x05 \x01(\x03R\fanswerTimeMs\"s\n" +
	"\x16CalculateScoreResponse\x12\x14\n" +
	"\x05score\x18\x01 \x01(\x01R\x05score\x12\x18\n" +
	"\acorrect\x18\x02 \x01(\bR\acorrect\x12)\n" +
	"\x10speed_multiplier\x18\x03 \x01(\x01R\x0fspeedMultiplier\"0\n" +
	"\x15GetLeaderboardRequest\x12\x17\n" +
	"\aroom_id\x18\x01 \x01(\tR\x06roomId\"J\n" +
	"\x16GetLeaderboardResponse\x120\n" +
	"\aentries\x18\x01 \x03(\v2\x16.quiz.LeaderboardEntryR\aentries*5\n" +
	"\x11MatchmakingStatus\x12\n" +
	"\n" +
	"\x06QUEUED\x10\x00\x12\x14\n" +
	"\x10ALREADY_IN_QUEUE\x10\x012\xfe\x01\n" +
	"\x12MatchmakingService\x12N\n" +
	"\x0fJoinMatchmaking\x12\x1c.quiz.JoinMatchmakingRequest\x1a\x1d.quiz.JoinMatchmakingResponse\x12Q\n" +
	"\x10LeaveMatchmaking\x12\x1d.quiz.LeaveMatchmakingRequest\x1a\x1e.quiz.LeaveMatchmakingResponse\x12E\n" +
	"\x10SubscribeToMatch\x12\x1d.quiz.SubscribeToMatchRequest\x1a\x10.quiz.MatchEvent0\x012\xed\x01\n" +
	"\vQuizService\x12Q\n" +
	"\x10GetRoomQuestions\x12\x1d.quiz.GetRoomQuestionsRequest\x1a\x1e.quiz.GetRoomQuestionsResponse\x12E\n" +
	"\fSubmitAnswer\x12\x19.quiz.SubmitAnswerRequest\x1a\x1a.quiz.SubmitAnswerResponse\x12D\n" +
	"\x10StreamGameEvents\x12\x1d.quiz.StreamGameEventsRequest\x1a\x0f.quiz.GameEvent0\x012\xaa\x01\n" +
	"\x0eScoringService\x12K\n" +
	"\x0eCalculateScore\x12\x1b.quiz.CalculateScoreRequest\x1a\x1c.quiz.CalculateScoreResponse\x12K\n" +
	"\x0eGetLeaderboard\x12\x1b.quiz.GetLeaderboardRequest\x1a\x1c.quiz.GetLeaderboardResponseB\x13Z\x11quiz-battle/protob\x06proto3"

var (
	file_proto_quiz_proto_rawDescOnce sync.Once
	file_proto_quiz_proto_rawDescData []byte
)

func file_proto_quiz_proto_rawDescGZIP() []byte {
	file_proto_quiz_proto_rawDescOnce.Do(func() {
		file_proto_quiz_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_quiz_proto_rawDesc), len(file_proto_quiz_proto_rawDesc)))
	})
	return file_proto_quiz_proto_rawDescData
}

var file_proto_quiz_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_quiz_proto_msgTypes = make([]protoimpl.MessageInfo, 25)
var file_proto_quiz_proto_goTypes = []any{
	(MatchmakingStatus)(0),           // 0: quiz.MatchmakingStatus
	(*JoinMatchmakingRequest)(nil),   // 1: quiz.JoinMatchmakingRequest
	(*JoinMatchmakingResponse)(nil),  // 2: quiz.JoinMatchmakingResponse
	(*LeaveMatchmakingRequest)(nil),  // 3: quiz.LeaveMatchmakingRequest
	(*LeaveMatchmakingResponse)(nil), // 4: quiz.LeaveMatchmakingResponse
	(*SubscribeToMatchRequest)(nil),  // 5: quiz.SubscribeToMatchRequest
	(*MatchEvent)(nil),               // 6: quiz.MatchEvent
	(*GetRoomQuestionsRequest)(nil),  // 7: quiz.GetRoomQuestionsRequest
	(*GetRoomQuestionsResponse)(nil), // 8: quiz.GetRoomQuestionsResponse
	(*Question)(nil),                 // 9: quiz.Question
	(*SubmitAnswerRequest)(nil),      // 10: quiz.SubmitAnswerRequest
	(*SubmitAnswerResponse)(nil),     // 11: quiz.SubmitAnswerResponse
	(*StreamGameEventsRequest)(nil),  // 12: quiz.StreamGameEventsRequest
	(*GameEvent)(nil),                // 13: quiz.GameEvent
	(*QuestionBroadcast)(nil),        // 14: quiz.QuestionBroadcast
	(*LeaderboardUpdate)(nil),        // 15: quiz.LeaderboardUpdate
	(*LeaderboardEntry)(nil),         // 16: quiz.LeaderboardEntry
	(*RoundResult)(nil),              // 17: quiz.RoundResult
	(*MatchEnd)(nil),                 // 18: quiz.MatchEnd
	(*PlayerResult)(nil),             // 19: quiz.PlayerResult
	(*PlayerJoined)(nil),             // 20: quiz.PlayerJoined
	(*TimerSync)(nil),                // 21: quiz.TimerSync
	(*CalculateScoreRequest)(nil),    // 22: quiz.CalculateScoreRequest
	(*CalculateScoreResponse)(nil),   // 23: quiz.CalculateScoreResponse
	(*GetLeaderboardRequest)(nil),    // 24: quiz.GetLeaderboardRequest
	(*GetLeaderboardResponse)(nil),   // 25: quiz.GetLeaderboardResponse
}
var file_proto_quiz_proto_depIdxs = []int32{
	0,  // 0: quiz.JoinMatchmakingResponse.status:type_name -> quiz.MatchmakingStatus
	9,  // 1: quiz.GetRoomQuestionsResponse.questions:type_name -> quiz.Question
	14, // 2: quiz.GameEvent.question:type_name -> quiz.QuestionBroadcast
	15, // 3: quiz.GameEvent.leaderboard:type_name -> quiz.LeaderboardUpdate
	17, // 4: quiz.GameEvent.round_result:type_name -> quiz.RoundResult
	18, // 5: quiz.GameEvent.match_end:type_name -> quiz.MatchEnd
	20, // 6: quiz.GameEvent.player_joined:type_name -> quiz.PlayerJoined
	21, // 7: quiz.GameEvent.timer_sync:type_name -> quiz.TimerSync
	16, // 8: quiz.LeaderboardUpdate.entries:type_name -> quiz.LeaderboardEntry
	19, // 9: quiz.MatchEnd.players:type_name -> quiz.PlayerResult
	16, // 10: quiz.GetLeaderboardResponse.entries:type_name -> quiz.LeaderboardEntry
	1,  // 11: quiz.MatchmakingService.JoinMatchmaking:input_type -> quiz.JoinMatchmakingRequest
	3,  // 12: quiz.MatchmakingService.LeaveMatchmaking:input_type -> quiz.LeaveMatchmakingRequest
	5,  // 13: quiz.MatchmakingService.SubscribeToMatch:input_type -> quiz.SubscribeToMatchRequest
	7,  // 14: quiz.QuizService.GetRoomQuestions:input_type -> quiz.GetRoomQuestionsRequest
	10, // 15: quiz.QuizService.SubmitAnswer:input_type -> quiz.SubmitAnswerRequest
	12, // 16: quiz.QuizService.StreamGameEvents:input_type -> quiz.StreamGameEventsRequest
	22, // 17: quiz.ScoringService.CalculateScore:input_type -> quiz.CalculateScoreRequest
	24, // 18: quiz.ScoringService.GetLeaderboard:input_type -> quiz.GetLeaderboardRequest
	2,  // 19: quiz.MatchmakingService.JoinMatchmaking:output_type -> quiz.JoinMatchmakingResponse
	4,  // 20: quiz.MatchmakingService.LeaveMatchmaking:output_type -> quiz.LeaveMatchmakingResponse
	6,  // 21: quiz.MatchmakingService.SubscribeToMatch:output_type -> quiz.MatchEvent
	8,  // 22: quiz.QuizService.GetRoomQuestions:output_type -> quiz.GetRoomQuestionsResponse
	11, // 23: quiz.QuizService.SubmitAnswer:output_type -> quiz.SubmitAnswerResponse
	13, // 24: quiz.QuizService.StreamGameEvents:output_type -> quiz.GameEvent
	23, // 25: quiz.ScoringService.CalculateScore:output_type -> quiz.CalculateScoreResponse
	25, // 26: quiz.ScoringService.GetLeaderboard:output_type -> quiz.GetLeaderboardResponse
	19, // [19:27] is the sub-list for method output_type
	11, // [11:19] is the sub-list for method input_type
	11, // [11:11] is the sub-list for extension type_name
	11, // [11:11] is the sub-list for extension extendee
	0,  // [0:11] is the sub-list for field type_name
}

func init() { file_proto_quiz_proto_init() }
func file_proto_quiz_proto_init() {
	if File_proto_quiz_proto != nil {
		return
	}
	file_proto_quiz_proto_msgTypes[12].OneofWrappers = []any{
		(*GameEvent_Question)(nil),
		(*GameEvent_Leaderboard)(nil),
		(*GameEvent_RoundResult)(nil),
		(*GameEvent_MatchEnd)(nil),
		(*GameEvent_PlayerJoined)(nil),
		(*GameEvent_TimerSync)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_quiz_proto_rawDesc), len(file_proto_quiz_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   25,
			NumExtensions: 0,
			NumServices:   3,
		},
		GoTypes:           file_proto_quiz_proto_goTypes,
		DependencyIndexes: file_proto_quiz_proto_depIdxs,
		EnumInfos:         file_proto_quiz_proto_enumTypes,
		MessageInfos:      file_proto_quiz_proto_msgTypes,
	}.Build()
	File_proto_quiz_proto = out.File
	file_proto_quiz_proto_goTypes = nil
	file_proto_quiz_proto_depIdxs = nil
}
